### ISSUE TITLE
API just support application/vnd.kafka.json.v2+json as content-type header

### ISSUE THREAD

**Issue by XI1876-ManojSharma** [confluentinc/kafka-rest#1000]
Hi,

API just support application/vnd.kafka.json.v2+json as content-type header, but I have an issue I can't provide a custom header. Can we have a default header for content-type as application/json?

**Comment by axisc** [comment]
@XI1876-ManojSharma For this functionality, please use v3 (for non-Consume use cases), [documentation](https://docs.confluent.io/platform/current/kafka-rest/api.html#records-v3)
