### ISSUE TITLE
Race condition when consuming while topic is being created

### ISSUE THREAD

**Issue by kjvalencik** [confluentinc/kafka-rest#105]
If you make a call to `POST /consumers/(string: group_name)/instances/(string: instance)/offsets`
while a topic is in the process of still being created you may get an exception due to this line:

https://github.com/confluentinc/kafka-rest/blob/d899a1eb1bc83d67cc9ebe0ec74195b0f11f6346/src/main/java/io/confluent/kafkarest/MetadataObserver.java#L185

The error is that this `Option` is empty.

In practice, this is likely not a concern, but it makes unit testing difficult because consumers may not be started until a topic has fully been created.

**Comment by hachikuji** [comment]
@kjvalencik Good catch. We definitely should be checking the option.

**Comment by ewencp** [comment]
I think there might be a couple of other cases of this same issue in that class as well. Should be easy to find them all with an IDE to search for uses of `Option.get()`

**Comment by rekhajoshm** [comment]
https://github.com/confluentinc/kafka-rest/pull/144

**Comment by michaelkirschbaum** [comment]
Has this been resolved?

**Comment by ewencp** [comment]
@michaelkirschbaum Yes, should be for at least this case since #144 was merged. If you're seeing another case where we're not checking an `Option` properly, please let us know.
