### ISSUE TITLE
Kafka Rest Proxy and ksqlDB STREAM INSERT behaviours are different

### ISSUE THREAD

**Issue by ozenakyurek** [confluentinc/kafka-rest#1081]
I'm using the latest confluent-7.3.0.tar.gz on Arch Linux
The following commands in ksqlDB is fine
`ksql>create stream ROOM_TEMPERATURE (
ROOM_ID   INTEGER,
ROOM_TEMP INTEGER
  ) WITH (
    KAFKA_TOPIC = 'ROOM_TEMPERATURE',
    PARTITIONS=2,
    VALUE_FORMAT = 'JSON'
  );
`
and 
`ksql>insert into ROOM_TEMPERATURE(ROOM_ID, ROOM_TEMP) values (1,24);`

And the following curl command line works fine as well
`curl --location --request POST 'http://localhost:8082/topics/ROOM_TEMPERATURE' \
--header 'Content-Type: application/vnd.kafka.json.v2+json' \
--data-raw '{
    "records": [
        {
            "value": [
                {
                    "ROOM_ID": 1,
                    "ROOM_TEMP": 25
                }
            ]
        }
    ]
}'`

When I run the following command line 
`kafka-console-consumer --topic ROOM_TEMPERATURE --from-beginning --bootstrap-server localhost:9092`

The output is
_{"ROOM_ID":1,"ROOM_TEMP":24}
**[**{"ROOM_ID":1,"ROOM_TEMP":25}**]**_

Notice the extra  "**[**" and "**]**" in the record which was inserted through Kafka-Rest.

And the latest record I've inserted using Kafka Rest is not visible from ksqlDB if I run the following command
`ksql> select * from ROOM_TEMPERATURE;`

And only 1 record is visible in ksqlDB side.

Is there any way to insert a record to my STREAM using Kafka-Rest like ksqlDB does?

**Comment by AndrewJSchofield** [comment]
This is a problem in the curl command.

`curl -X POST http://localhost:8082/topics/T1 -H 'Content-Type: application/vnd.kafka.json.v2+json' -d '{ "records": [ { "value": [ { "ROOM_ID": 1, "ROOM_TEMP": 25 } ] } ] }'` gives a message `[{"ROOM_ID":1,"ROOM_TEMP":25}]`.

`curl -X POST http://localhost:8082/topics/T1 -H 'Content-Type: application/vnd.kafka.json.v2+json' -d '{ "records": [ { "value": { "ROOM_ID": 1, "ROOM_TEMP": 25 } } ] }'` gives a message `{"ROOM_ID":1,"ROOM_TEMP":25}`.
