### ISSUE TITLE
Create a topic via API method

### ISSUE THREAD

**Issue by ducas** [confluentinc/kafka-rest#109]
As a client I would like to create a topic by making a request to the API so that I can specify partitions, replication factor and other configuration options.

### PUT /topics/(string: topic_name)
_Parameters_
* topic_name (string) - The topic to consume messages from.

_Request JSON Object_
* partitions (int) - The number of partitions the topic will have
* replication_factor (int) - The replication factor of the topic
* config (object) - The configuration to use for this topic (see [Kafka Topic Config](http://kafka.apache.org/documentation.html#topic-config) for all options)

#### Example Request
    PUT /topics/test_topic/ HTTP/1.1
    Host: kafkaproxy.example.com
    Accept: application/vnd.kafka.v1+json, application/vnd.kafka+json, application/json
    {
      "partitions": 40,
      "replication_factor": 10,
      "config": {
        "flush.ms": 50
      }
    }

**Comment by kjvalencik** [comment]
I believe this is a duplicate of https://github.com/confluentinc/kafka-rest/issues/3

**Comment by ducas** [comment]
Yep... I'll add some comments. Thanks @kjvalencik! :-)

**Comment by ducas** [comment]
duplicate of #3
