### ISSUE TITLE
Support for Basic Auth

### ISSUE THREAD

**Issue by apg** [confluentinc/kafka-rest#115]
I'd like to have support for Basic Auth. The Kafka Rest server would exist behind a TLS terminated connection, so this is not an issue.

My instinct tells me that this can be done by adding a new Servlet Filter, in reality, probably in rest-utils, but I'm wondering if there's a simpler way? Is it the case that some magic xml file can just be placed somewhere and things just work?

**Comment by Mogztter** [comment]
You can do it (at least with confluent 3.2.0).
Given the following configuration:

.kafka-rest.properties
```
listeners=https://0.0.0.0:8081

ssl.keystore.location=/path/to/keystore.jks
ssl.keystore.password=password
ssl.key.password=password
ssl.truststore.location=/path/to/keystore.jks
ssl.truststore.password=password

authentication.method=BASIC
authentication.realm=KafkaServer
authentication.roles=admin
```

.jaas.config
```
KafkaServer {
    org.eclipse.jetty.jaas.spi.PropertyFileLoginModule required
    debug="true"
    file="/path/to/users.properties";
};
```

.users.properties
```
admin: admin,user,admin
```

```
KAFKAREST_OPTS="-Djava.security.auth.login.config=/path/to/jaas.config" ./bin/kafka-rest-start /path/to/kafka-rest.properties
```

You should be able to authenticate with `admin:admin` on `https://your-server:8081`

**Comment by rangwea** [comment]
I want to add a Custom Servlet Filter,can I?

**Comment by dharaneeshvrd** [comment]
@Mogztter 
I have tried this basic auth with ```org.eclipse.jetty.jaas.spi.PropertyFileLoginModule```. Everything seems to be working fine.

But if I use ```org.eclipse.jetty.jaas.spi.ReloadablePropertyFileLoginModule``` 
(like mentioned here https://docs.rundeck.com/docs/administration/security/authentication.html#hot-reloading-the-realm-properties-file which is pointed out in official doc)
the authentication is not setup. I am not able to use the user and password given in users.properties file. I could not see any console logs associated with this also. 

Do you know whether any other login module is supported in basic auth? or How can I make this ```ReloadablePropertyFileLoginModule``` work?
