### ISSUE TITLE
Null key values with JSON Format

### ISSUE THREAD

**Issue by dalassi** [confluentinc/kafka-rest#121]
Hi,
I have tried a version of the REST service that I built myself from master as I needed JSON support. I noticed that if you don't specify a key, i.e. key is null, messages would be published always to the same partition. I tracked this down and found that the Jackson JSON parser seems to have a bug where you pass in key as null but returns back a byte[] with 110,117,108,108 which UTF-8 translates to "null". The binary parser/converter works fine as it still returns NULL and then the REST service uses a Round Robin approach for these NULL values.

**Comment by hachikuji** [comment]
Thanks for the bug report. Looks like we need to add a null check inside `KafkaJsonSerializer`, which lives in schema-registry.

**Comment by hachikuji** [comment]
Closing this issue since it was resolved in https://github.com/confluentinc/schema-registry/pull/264. We'll try to get this included in the next release.
