### ISSUE TITLE
Producer replication factor question

### ISSUE THREAD

**Issue by inadler** [confluentinc/kafka-rest#124]
How can I control the producer's "request.required.acks" parameter?

I want to wait for the publish response until at least one replication happend.
Kafka producer configuration contains this parameter, but I cannot find a way to control it using the rest proxy.

**Comment by ewencp** [comment]
@inadler You can pass producer and consumer configurations directly in the kafka-rest configuration. See the [overview of configuration options](http://docs.confluent.io/1.0.1/kafka-rest/docs/config.html#configuration-options) in the docs for more detail about how this works and interacts with settings that are exposed directly in the API.

**Comment by inadler** [comment]
I see, so just to make sure I understand it correctly:
I need to add "producer.request.required.acks=-1" to the proxy config.
Is that correct?

**Comment by ewencp** [comment]
We use the new producer in the REST proxy. You pass the config directly, so just adding `acks=all` should work.

**Comment by inadler** [comment]
Thank you

**Comment by inadler** [comment]
Again, I am not sure I understand it correctly, should I add the "producer" prefix ? 
i.e. "producer.acks=all" or just acks=all ?
Your documentation is not clear here.

**Comment by thieman** [comment]
Hi @ewencp, could you please confirm whether `acks=all` is also the correct setting for proxy v1.0?

**Comment by ewencp** [comment]
@thieman Should work fine for 1.0 too -- both versions use the new producer.
