### ISSUE TITLE
Found some bugs when testing tes KAFKA REST API

### ISSUE THREAD

**Issue by lukemao** [confluentinc/kafka-rest#126]
It allows me to produce messages with two keys:
Request:
{"records":[{"key":"a2V5", "key":"a2V6","value":"S2Fma2E="}]}
Response:
{
  "offsets": [{
    "partition": 0,
    "offset": 0,
    "error_code": null,
    "error": null
  }],
  "value_schema_id": null,
  "key_schema_id": null
}

When consume the message I get:
{"array": [{
  "partition": 0,
  "offset": 0,
  "value": "S2Fma2E=",
  "key": "a2V6"
}]}

**Comment by ewencp** [comment]
This is actually an issue in confluentinc/rest-utils being addresed in https://github.com/confluentinc/rest-utils/pull/29
