### ISSUE TITLE
produce message with more than one keys

### ISSUE THREAD

**Issue by lukemao** [confluentinc/kafka-rest#143]
After running some test against the Kafka Rest, I found that I can produce a message more than one keys, e.g.{\"key\":\"a2V5\", \"key\":\"a2V6\",\"value\":\"S2Fma2E=\"}
a2V6 will be used as the message key.
This is the way that Jackson JSon parser does when find duplicated key.

I want to patch the kafka rest with additional validation against the HTTP request body.

Is  JacksonMessageBodyProvider the place to add such validation? this is in rest-utils
I can see the readFrom method that call the overriden method in superclass JacksonJaxbJsonProvider.

**Comment by ewencp** [comment]
@lukemao Potentially. I think the way to address this is to set the `FAIL_ON_READING_DUP_TREE_KEY` deserialization option to true. This could potentially be made the default for the default constructor in `JacksonMessageBodyProvider`. However, the `Application` class in rest-utils passes in an `ObjectMapper` instance to the `JacksonMessageBodyProvider`, so you'd have to either change it to use the default or make the change in the `Application` class.

You'll have to check what type of error it throws for that error too -- it may require additional handling to convert it into an appropriate `WebApplicationException` so it generates the correct error type.

**Comment by lukemao** [comment]
Hi @ewencp , Happy new year.
Thanks for the reply and hint for the change be made. 
I am not sure about when you mentioned  '... convert it into an appropriate `WebApplicationException`' in your reply what error should be thrown. Maybe if you can, to elaborate a bit more. 
I would enable the duplicate check by the `ObjectMapper` in the `Application` class.  I will add a try and catch block in the `readFrom' method in the class `JacksonMessageBodyProvider` if the parse found a duplicate key.  In the catch block I would through a 'converted WebApplicationException' error

**Comment by ewencp** [comment]
@lukemao There's a set of exceptions that Jersey uses to convert to HTTP status codes. We actually augment that a bit because they don't include all the error codes. In this case, you probably want to use a `ConstraintViolationException` which will get translated into a `422 Unprocessable Entity` error. Other code in `JacksonMessageBodyProvider` already uses this via the `ConstraintViolations.simpleException` helper method, which you might also want to use.

**Comment by lukemao** [comment]
Thanks for the indication.
