### ISSUE TITLE
Add allow/deny list for topics

### ISSUE THREAD

**Issue by fhussonnois** [confluentinc/kafka-rest#151]
It would be nice to have properties to configure either a blacklist or whitelist of topics.
This way the messages can be produced or consumed only for allowed topics.

The endpoint /topics could be modified to return only the available topics.

**Comment by kai-kzh** [comment]
Agree, especially on consumer side, blacklist and whitelist will be very helpful.

**Comment by karux** [comment]
+1 . the existing wide open scheme is preventing defense in depth, and prevents tailoring the REST proxy topic publication per partner.

**Comment by axisc** [comment]
This is best managed by the ACLs which I feel is the preferred option for the Operator persona.

I'm closing this since this is an older issue. Please feel free to open a fresh issue if there is a preference for allow/deny list for topics within the REST Proxy configuration.
