### ISSUE TITLE
Question about partitions re-balancing scenario

### ISSUE THREAD

**Issue by inadler** [confluentinc/kafka-rest#153]
I encountered with a scenario which I would like to get explanation on: 

- Create a topic with 2 partitions.
- Create 2 consumers on the same consumer group (A & B)
- Post 2 messages into the topic one to each partition - message "0" into partition 0 and message "1" into partition 1
- Consumer A read message "0" from a partition 0
- Consumer B read message "1" from a partition 1     =>  so far so good
- Delete consumer A   

Now, due to re-balancing, consumer B reads messages from both partitions, so I would expect consumer B to read message "0" from partition 0 (because consumer A didn't send offset commit yet) - but it doesn't read it again - why is that?

- Delete consumer B 
- Re-create consumer A
- Consumer A read both message ("0" and "1") from both partitions 0 and 1   
    =>  Why? we already read those 2 messages before.

- Re-create consumer B
- Consumer A read message "0" from a partition 0 again and consumer B read message "1" from a partition 1 again  
   => why is that? we already read those messages before.

My guess is that while there is at least one consumer on a group, the offset doesn't get reset - is that correct?

**Comment by ewencp** [comment]
@inadler Not sure if you resolved this on your own, but it sounds like auto commit might be enabled. When it is enabled, clean shutdown of consumers will commit offsets. You can disable it in the initial `POST` that creates the consumer instances by including a field `"auto.commit.enable": "false"` in the request body.

**Comment by inadler** [comment]
@ewencp, thanks you for your quick answer.
I closed it because I realized that I was using "auto.offset.reset=largest" and since I was consuming from a new consumer group, no one has ever committed an offset yet, so I was keep getting the topic from start.
