### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by mpharding** [confluentinc/kafka-rest#160]
Hi,
Is there a time estimate on when security will be added the to REST proxy? Given there isn't any way to secure the API is there any other options in terms of securing requests in the short term?

Thanks,
Mike

**Comment by ewencp** [comment]
@hardboy111 We don't have an exact timeframe on this. We know there are people looking for security. Could you also be more specific about what security you're looking for? Wire encryption (e.g. SSL)? Do you need authn/authz on the API itself? And what about the connection to Kafka itself? There are a lot of places and ways security could be added, so it's helpful to have a better idea of what you want secured.

**Comment by hardboy111** [comment]
Thanks for the info - specifically I want to be able to authenticate/authorise requests to the REST API. So ideally something akin to Basic HTTP Auth or token based Auth. My use case is that I have a sensor network gateway pushing data into a Kafka topic. Ideally I'd like to use HTTP as the communication and kafka-rest works great but the inability to secure POST requests would result in looking for an alternative.

**Comment by cmcbugg** [comment]
The Confluent documentation describes Kafka broker security using SASL (kerberos),   but there is nothing detailed in the Schema Registry or Kafka Rest Proxy documentation around using SASL secured Kafka brokers.     Does the Schema Registry & Rest Proxy work with secured brokers?

**Comment by criccomini** [comment]
We are also very interested in this.

**Comment by criccomini** [comment]
There are two primary aspects I am interested in from security requirements perspective.

1. Encryption: The traffic between services and Kafka rest proxy should be encrypted. Traffic between Kafka components should be encrypted.
2. Authentication: Service to service authentication between Kafka and other services (e.g. basic auth)

I think (1) can be accomplished just by throwing an SSL termination point like NGinx in front of the proxy. (2) requires real support.

**Comment by TattiQ** [comment]
Hello! 

Anything changed with respect to  securing  POST requests to kafka-rest proxy? We are looking for an easy way to authenticate e.g. send a jwt token to the proxy or smth like that.

**Comment by brandonwittwer** [comment]
Basic auth is functional currently. I recommend closing this issue.

https://docs.confluent.io/current/security/basic-auth.html
