### ISSUE TITLE
MetadataObserver.topicExists gets information for all the topics 

### ISSUE THREAD

**Issue by cpuchakayaka** [confluentinc/kafka-rest#162]
ConsumersResource.readTopic checks if the topic exists by calling MetadataObserver.topicExists before reading messages. MetadataObserver.topicExists calls the getTopicsData for all the topics not just the topic that being read from. This adds extra latency 25 seconds for our request times.

Our setup is 30 topics, 50 partitions for each topic, 3 node kafka cluster ,1 zookeeper.

I don't see need to get all the topic info like partition,leader,isr, just checking topicName exists should enough, and even that could be cached, as there is no need to check if topic exists for long running consumer instances.

**Comment by ducas** [comment]
:+1 this has been our biggest issue with rest proxy. When we we dropped
appdynamics onto it we found this was taking very large amounts of time
constantly. Not a good thing to have in a web application…
On Fri, 11 Mar 2016 at 07:40, K.J. Valencik <notifications@github.com>
wrote:

> I can confirm that this is definitely a massive bottleneck. I just did a
> test where I changed the following like to if (false) { and batch times
> dropped from 10-30 seconds to sub-second.
>
>
> https://github.com/confluentinc/kafka-rest/blob/326e269b301e1439ebfabafc4533c5d7d7272190/src/main/java/io/confluent/kafkarest/ConsumerManager.java#L240
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/confluentinc/kafka-rest/issues/162#issuecomment-195037106>
> .
>
-- 
Cheers,
Ducas

**Comment by ewencp** [comment]
Fixed by #202
