### ISSUE TITLE
Is Kafka Rest a good fit?

### ISSUE THREAD

**Issue by mindscratch** [confluentinc/kafka-rest#168]
I wasn't sure if there was a mailing list or group to ask this question to, so I thought I'd ask here.
1. If the data I'm putting into Kafka is either binary or JSON, do I need to run a Schema Registry?
2. If I have a topic with 2 partitions, and I have hundreds of instances of an app that all want to process that one topic (as the same group), would kafka rest balance the consumption properly so I don't have apps sitting idle?

Thanks

**Comment by ewencp** [comment]
@mindscratch Confluent has a [mailing list](https://groups.google.com/forum/#!forum/confluent-platform) to help answer questions like these.

1. No, you do not need to run the schema registry in that case.

2. Kafka consumers split work on a per-partition basis, so the maximum number of active consumers you can have in a consumer group is the same as the total number of partitions you are consuming. If you want more parallelism, you'll need to use more partitions. (Note that this is true of all consumers, not just the REST proxy).

**Comment by jeffwidman** [comment]
I think this can be closed?
