### ISSUE TITLE
Useless error messages when trying to run /usr/bin/kafka-rest-start

### ISSUE THREAD

**Issue by aragnon** [confluentinc/kafka-rest#177]
This error message is _completely_ useless. Please correct this. 

```
ERROR Server died unexpectedly: org.apache.kafka.common.KafkaException: Failed to construct kafka producer (io.confluent.kafkarest.KafkaRestMain:44)
```

**Comment by aragnon** [comment]
I don't care about help on this topic anymore, but I would like to see it fixed. Unsubscribing.

**Comment by no1youknowz** [comment]
I got this message as well.  What I was doing, was only installing kafka from the tgz and not installing everything else.

So I figured that I would install the open source confluent repo of applications.  

I then started the apps in order of sequence and each in their own terminal:

    zookeeper-server-start ./etc/kafka/zookeeper.properties
    kafka-server-start ./etc/kafka/server.properties
    schema-registry-start ./etc/schema-registry/schema-registry.properties
    kafka-rest-start etc/kafka-rest/kafka-rest.properties

The rest proxy should say: 

    [2017-03-27 06:50:34,565] INFO Server started, listening for requests... (io.confluent.kafkarest.KafkaRestMain:53)

Now it's working.

**Comment by ewencp** [comment]
Thanks @no1youknowz. I think the source of that error is often that the bootstrap servers cannot be resolved (e.g. if you hadn't started the broker yet), which the producer checks when starting up. If none of the bootstrap servers can be resolved, it will error out in this way.
