### ISSUE TITLE
Bug on your blog

### ISSUE THREAD

**Issue by aragnon** [confluentinc/kafka-rest#180]
The code you have on your website contains an invalid curl command, because you missed a line-continuation character. 

On this page: 
http://www.confluent.io/blog/a-comprehensive-open-source-rest-proxy-for-kafka/

I think it communicates a certain laziness when you aren't even testing your own code in your marketing material.

**Comment by ewencp** [comment]
The blog was automatically translated from our previous CMS and it seems some formatting got mildly broken. You didn't specify which command was failing, but I've removed the one case of an extra, unintended newline in the commands that I could find.
