### ISSUE TITLE
Latest commit used with kafka 8.x

### ISSUE THREAD

**Issue by nguyenxuantuong** [confluentinc/kafka-rest#185]
Hi,

I want to check if it's possible to build latest commit for kafka 8.x. Seems that the latest code only works with kafka 9.x (it throws the error with kafka 8.x for recent commits. For latest commit, I was not even able to build due to dependency problems of schema-registry and common dependencies ). How I can make it work with kafka 8.x

Thanks.

**Comment by ewencp** [comment]
@nguyenxuantuong At the moment the code is pinned to the version of Kafka that will be released next. We use a few internals that will restrict the versions you can build with, although at the moment we aren't using any features that didn't exist in 0.8 releases. You might be able to revert a couple of PRs that made updates to 0.10 versions and get a working build for 0.8

**Comment by Antwnis** [comment]
I think this ticket adds no value by remaining open
+1 on closing it
