### ISSUE TITLE
Kafka REST zookeeper conflicts

### ISSUE THREAD

**Issue by cpuchakayala** [confluentinc/kafka-rest#193]
We have 14 Kafka Rest nodes, and have like 50 clients interacting with Kafka Rest cluster, during unclean shutdown of Kafka Rest nodes we keep running into consumer rebalance exceptions. Once this happens the only way out of this is to shutdown all the clients and shutdown Kafka Rest nodes and restart all of them. There is few mins of window where we loose traffic, which we need to avoid. From what I have observed during the unclean shutdown of Kafka Rest,  znodes (consumer instance znodes in consumer group) in Zookeeper don't get removed even after Zookeeper session timeout and during consumer rebalance, it tries to rebalance with the dead consumers in Zookeeper and fails, probably is related to https://issues.apache.org/jira/browse/KAFKA-1585. 

What is the recommend version for Zookeeper for Kafka Rest?

Our consumer rebalance settings are 
consumer.rebalance.max.retries = 10
consumer.rebalance.backoff.ms = 2000

Kafka version 0.9.0.0
Zookeeper version is 3.4.5
Kafka Rest version is 2.0.0

Zookeeper session timeout is 30 seconds

When is the plan for Kafka Rest to use new consumer introduced in Kafka 0.9.0.0 which doesn't go thru zookeeper at all. I will be happy to send a pull request for this, but it will be breaking changes form the current implementation as their will be no KafkaStream, ConsumerIterator (need to adapt this one to use consumer.poll())

**Comment by jmarcos-cano** [comment]
@cpuchakayaka it's been a hile here, just curious on how you set up those 14 messages? 

regarding: id, and hostname .

thanks
