### ISSUE TITLE
kafka-rest cannot register new schema

### ISSUE THREAD

**Issue by ycui1984** [confluentinc/kafka-rest#196]
We execute example like in the Readme.md
curl -X POST -H "Content-Type: application/vnd.kafka.avro.v1+json"       --data '{"value_schema": "{\"type\": \"record\", \"name\": \"User\", \"fields\": [{\"name\": \"name\", \"type\": \"string\"}]}", "records": [{"value": {"name": "testUser"}}]}'       "http://localhost:8082/topics/xyz"   
xyz is a brand new topic, we got the error of {"error_code":40801,"message":"Schema registration or lookup failed"}. After some googling, we noticed that some people reported it here. https://groups.google.com/forum/#!topic/confluent-platform/c-PJ3YQU7Kk
However, after a close investigation, we do not have exactly the same problem with theirs. 
Their problems are caused by using a different port for the service, but we used the default ports of confluent.io. Also, different from the problem reported, there is no schema registered in the schema service.  We used confluent.io 2.0. It will be helpful if any insights are provided.

**Comment by ewencp** [comment]
@ycui1984 This request is working fine for me locally just by spinning up Kafka, schema registry, and REST proxy and then copy-pasting your command. Can you check the schema registry and REST proxy logs to see if any additional info is reported there? On the REST proxy you can also set `debug=true` in your config and it might include more error info in the response.

**Comment by ycui1984** [comment]
Thanks @ewencp ! we enabled debug, it's really helpful, 
it turns out we did not specify http protocol in the schema registry config
