### ISSUE TITLE
not able tto compile

### ISSUE THREAD

**Issue by zohakhan6** [confluentinc/kafka-rest#198]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project kafka-rest: Compilation failure: Compilation failure:
[ERROR] /home/zoha/workspaceFolder/test/kafka-rest/src/main/java/io/confluent/kafkarest/SimpleConsumerManager.java:[189,8] error: cannot infer type arguments for MessageAndMetadata<>
[ERROR] reason: cannot infer type-variable(s) K,V
[ERROR](actual and formal argument lists differ in length)
[ERROR] where K,V are type-variables:
[ERROR] K extends Object declared in class MessageAndMetadata
[ERROR] V extends Object declared in class MessageAndMetadata

**Comment by ewencp** [comment]
What JDK are you using? This compiles fine with the Oracle JDK and the line it is referring to appears like a straightforward use of diamond syntax and the types should be inferrable via the decoder parameters which use the generic types.
