### ISSUE TITLE
Poor throughput compared to native API

### ISSUE THREAD

**Issue by pranab** [confluentinc/kafka-rest#199]
I did some performance bench marking with REST server and compared  them to native call performance. Throughput difference is significant. For consumers it's as much as 90% throughput drop compared to native calls. Here is my environment

3 node cluster (Intel Xeon 2.4 GHz CPU, 8 GB RAM)
3 Kafka nodes
2 zookeeper nodes
1 REST server node.
2 topics
2 publishers, each writing  to separate topic
8 consumers, 4 for each topic
average message size 30K
publisher and consumer calls are sustained, back to back

I am going to have a load balancer ahead of the REST server and have a cluster of REST servers to improve the performance. Because consumers are statefull in REST, I need to have sticky load balancing right?

Anything else I can do to improve throughput?

**Comment by stephlag** [comment]
I'm also experiencing poor performance with the producer.
When I'm using Confluent Rest Proxy to send json messages I have a rate of 226 messages/s (no batching) while with my own proxy I have a rate of 1935 messages/s.

**Comment by jasonparekh** [comment]
@pranab did you find a way to improve performance?

**Comment by pranab** [comment]
I was able to improve REST performance by

1. Having a REST cluster and a sticky load balancer in front
2. Increase max.partition.fetch.bytes so that consumers can get multiple messages per call

Now the REST producer throughput is about 25% of native. For consumer it's 20% of native
