### ISSUE TITLE
Performance testing

### ISSUE THREAD

**Issue by nehanarkhede** [confluentinc/kafka-rest#2]

**Comment by stavpie** [comment]
Hello @ewencp, sorry for this silly question but how can we use ProducerPerformance and ConsumerPerformance in order to execute perfomance tests? I have searched into the repo and I was not able to find any instructions.

**Comment by stanislavkozlovski** [comment]
Hey there @stavpie,

You are correct that we are missing documentation on how to run these performance tools. Let me help unblock you - the way you use them is via the `./bin/kafka-rest-run-class` script.

An example:
```
~/Documents/code/kafka-rest -  (master) $ ./bin/kafka-rest-run-class io.confluent.kafkarest.tools.ProducerPerformance

> Usage: java io.confluent.kafkarest.tools.ProducerPerformance rest_url topic_name num_records record_size batch_size target_records_sec
```

An example with 100 records, each of size 100 produced to the `topic_name` topic:
```
 ~/Documents/code/kafka-rest -  (master) $ ./bin/kafka-rest-run-class io.confluent.kafkarest.tools.ProducerPerformance http://localhost:8013 topic_name 100 100 100 100
100 records processed, 81.900082 records/sec (0.01 MB/sec), 8.90 ms avg latency, 890.00 ms max latency, 890 ms 50th, 890 ms 95th, 890 ms 99th, 890 ms 99.9th.
```

**Comment by stavpie** [comment]
Thanks a lot @stanislavkozlovski :)
