### ISSUE TITLE
Consumer instance not found

### ISSUE THREAD

**Issue by ycui1984** [confluentinc/kafka-rest#201]
Hi kafka-rest developers,
    We encountered a strange problem of kafka-rest. 
What we did was,
1. post new data into a topic
curl -X POST -H "Content-Type: application/vnd.kafka.avro.v1+json"       --data '{"value_schema": "{\"type\": \"record\", \"name\": \"User\", \"fields\": [{\"name\": \"name\", \"type\": \"string\"}]}", "records": [{"value": {"name": "testUser"}}]}'  http://<host:port>/topics/avrotest
2. create a brand new consumer(the consumer has never been created before)
curl -X POST -H "Content-Type: application/vnd.kafka.v1+json"       --data '{"name": "my_consumer_instance", "format": "avro", "auto.offset.reset": "smallest"}'       http://<host:port>/consumers/newconsumer
3. pull data from the topic using the consumer
curl -X GET -H "Accept: application/vnd.kafka.avro.v1+json"       http://<host:port>/consumers/txt/instances/my_consumer_instance/topics/avrotest

1 and 2 are successful. We run 3 multiple times, 
some times it can output our data, but most of times, it returns immediately with {"error_code":40403,"message":"Consumer instance not found."}
Any ideas of this issue?

**Comment by ycui1984** [comment]
a typo in 3,
curl -X GET -H "Accept: application/vnd.kafka.avro.v1+json" http://host:port/consumers/newconsumer/instances/my_consumer_instance/topics/avrotest

**Comment by ewencp** [comment]
Is this with a single instance of the REST proxy or for a cluster with multiple hosts? Make sure you are using the URL returned in step 2 to construct the URL in step 3 -- the instance is tied to the particular instance it was created on so the URL must point to the same instance of the REST proxy.

**Comment by ycui1984** [comment]
yeah, we found the problem and we set the host.name to let rest proxy return a url with hostname, so that they can access correctly. One more question though: is there any way to specify port also, because rest proxy is deployed behind load balancer and we use host name instead of host + port in load balancer to refer the service.   We tried to set host.name = host:port, but rest proxy gives us  host%3Aport

**Comment by ewencp** [comment]
@ycui1984 The port config is not available today, but is already being tracked here: https://github.com/confluentinc/kafka-rest/issues/149
