### ISSUE TITLE
standalone jar

### ISSUE THREAD

**Issue by dgonzalez** [confluentinc/kafka-rest#206]
Hi,
I am trying to build the standalone jar but it is quite challenging as the network at my workplace is quite restrictive as well as the different dependencies that kafka-rest relies on.

Would be possible to publish the standalone jar (for the kafka-rest) somewhere so it is easier to use?

**Comment by ewencp** [comment]
Unfortunately we can not due to licensing restrictions on some of the dependencies. It's possible to compile yourself and use it as long as you don't redistribute it, however.
