### ISSUE TITLE
unable to send a large message

### ISSUE THREAD

**Issue by gregorleban** [confluentinc/kafka-rest#208]
Hi,
I'm using the kafka-rest in Confluent 3.0.0 on Ubuntu. I've changed the following properties in:
`server.properties`:
```
message.max.bytes=15728640
replica.fetch.max.bytes=15728640
max.request.size=15728640
fetch.message.max.bytes=15728640
```

and `producer.properties`:
```
max.request.size=15728640
```

but I still get the following error when posting a large message:

The message is 1978246 bytes when serialized which is larger than the maximum request size you have configured with the max.request.size configuration.

I was looking at the source code of kafka-rest but don't see any property there that I could change. Can you please suggest what can I modify to increase the limit?
Thank you in advance for any help!

**Comment by gregorleban** [comment]
I think I have just solver my own problem. I needed to add the following line also to the `kafka-rest.properties` file:
```
# the maximum size of a request in bytes
max.request.size=15728640
```
Now I don't get the errors anymore.

**Comment by ewencp** [comment]
Yes, this solution is correct. If you want to increase the maximum message size, you always have to increase it in all 3 places: producer, broker, and consumer.

**Comment by ahmetbardiz** [comment]
I could not find these parameters in confluent 3.3.0. I have forced to add parameters and set like above but nothing changes again I am getting the RecordTooLargeException.

**Comment by srinivasj1122** [comment]
Hi Everybody
I am also facing the same above issue. Even after assigning 
# the maximum size of a request in bytes
max.request.size=15728640
I am getting the same Message(The message is 1978246 bytes when serialized which is larger than the maximum request size you have configured with the max.request.size configuration)
I Observed that Kafka server is not at all taking the values from the properties files. It is taking only the initialized values. As i didn't find my changed values in the logs.

Can any one please help me in this case.

As i am using kafka and spring cloud data flow
