### ISSUE TITLE
Consumer instance not found

### ISSUE THREAD

**Issue by nathan-zhu** [confluentinc/kafka-rest#211]
hi, I use confluent 3.0 version.

during i test restful proxy create topic and consumer, it works but after few hours my consumer disappeared get error below

`
      curl -X GET -H "Accept: application/vnd.kafka.json.v1+json" \
      http://10.216.90.225:8082/consumers/guazi_consumer2/instances/guazi_instance2/topics/guazi
{"error_code":40403,"message":"Consumer instance not found."}%
`

i didn't delete my consumer, how to keep consumer use for long time?
i use tool to check my consumer list guazi_consumer2 still there, why the instance get error? 

please help on it thanks

**Comment by ewencp** [comment]
If you didn't access the consumer instance for a few hours, it timed out and was cleaned up. See the `consumer.instance.timeout.ms` setting (http://docs.confluent.io/3.0.0/kafka-rest/docs/config.html) to control how long consumer instances will be kept alive even if no data is consumed. It defaults to 5 minutes.

Note that you usually don't want to set this value too high. If the process consuming from an instance dies but the consumer is kept alive, then the partitions it is assigned will not be reassigned to another member of the consumer group until the instance is removed, which means data in those partitions will not be processed until the application accessing that consumer instance is revived.

**Comment by nathan-zhu** [comment]
@ewencp thanks for help on it, i got it.
