### ISSUE TITLE
only able receive 1k message count per topic

### ISSUE THREAD

**Issue by limwesley** [confluentinc/kafka-rest#217]
i used confluent 1.0.1 due to project requirement required kafka 0.8.2.1 for consumer, 
i try running a performance test on confluent, it only able to receive 1k message count per topic 
every topic that reach 1k message count will hit error 500, 
**{
  "error_code": 500,
  "message": "Internal Server Error"
}**
if topic not reached 1k message count, it will not hit above error, did try to increase/ decrease message size still remain the same

**Comment by ewencp** [comment]
Are you using Avro? It sounds like you might be bumping up against an issue with the maximum cache size in the serializer/deserializer. Because it's an IdentityHashMap internally, you can exceed the size of the cache. How many schemas are used in the data you're consuming?

**Comment by limwesley** [comment]
@ewencp i used 1 schemas and 1 kafka rest

**Comment by limwesley** [comment]
@ewencp is there any config i need to change ?

**Comment by ewencp** [comment]
@limwesley The serializer/deserializer have a `max.schemas.per.subject` setting that you can increase from its default of 1000. That will fix the problem if you just have more than 1000 schemas used in the topic.

**Comment by limwesley** [comment]
@ewencp thanks will try it out !

**Comment by crumley** [comment]
Correct me if I am wrong but increasing the `max.schemas.per.subject` will only kick the can further down the road... You will either hit the new limit or run out of memory.

**Comment by ewencp** [comment]
Fixed in #222
