### ISSUE TITLE
Decode binary values before sending records to Kafka

### ISSUE THREAD

**Issue by fhussonnois** [confluentinc/kafka-rest#219]
Currently, binary values passed to producer must be encoded to base64. 

Am I right that this string isn't decoded before being sent to kafka ? 

In case, we directly send avro values as binary stream we are forced to change avro deserializer used in consumers to decode base64.

It could be more suitable to decode base64 values before sending records to kafka ?

**Comment by ewencp** [comment]
@fhussonnois The data is decoded before it is passed to Kafka. It will not be base64-encoded when written to Kafka. base64 is just used to make it safe to embed in the JSON request payload.
