### ISSUE TITLE
Couldn't download dependencies from "http://packages.confluent.io/maven/"

### ISSUE THREAD

**Issue by robinmisfit** [confluentinc/kafka-rest#227]
I removed my personal settings.xml and found maven couldn't download any dependencies from " http://packages.confluent.io/maven/".

**Comment by ewencp** [comment]
Can you include more information about the error? This works for all our Java projects, so it is likely either an issue with the dependency being specified (e.g. incorrect name or version) or a network connectivity issue.

**Comment by robinmisfit** [comment]
Hi @ewencp 

The code is master and clean. Also I removed my personal "settings.xml". I used Intellij and repos is as below. There is only "resolver-status.properties" in local repo and the content is 

> #NOTE: This is an internal implementation file, its format can be changed without prior notice.
#Thu Jul 28 14:57:01 CST 2016
maven-metadata-repo.xml.error=
maven-metadata-repo.xml.lastUpdated=1469689021743

![image](https://cloud.githubusercontent.com/assets/19645260/17236129/4ead3734-5579-11e6-96ee-60119c84b4dc.png)


I checked the target url in chrome and still couldn't find it, i.e http://packages.confluent.io/maven/io/confluent/rest-utils/3.1.0-SNAPSHOT/rest-utils-3.1.0-SNAPSHOT.jar

Thanks for your help

**Comment by ewencp** [comment]
@robinmisfit I see. This isn't really an issue with `packages.confluent.io`. We don't publish SNAPSHOT versions into that repository, but sometimes on `master` we need to depend on unreleased versions of upstream projects (Kafka, rest-utils, etc). During that development period, you'll need to build and install those SNAPSHOT dependencies yourself.

See https://github.com/confluentinc/kafka-rest/wiki/FAQ for more details.

**Comment by robinmisfit** [comment]
@ewencp Thanks for your answer, it works now 👍
