### ISSUE TITLE
Couldn't access REST server through https

### ISSUE THREAD

**Issue by robinmisfit** [confluentinc/kafka-rest#228]
I started a standalone confluent rest server(3.0.0-2.11,no DNS name is assigned) , with configurations like below:

>  id=kafka-rest-test-server
   debug=true
  #schema.registry.url=http://localhost:8081
  zookeeper.connect=localhost:2181
  listeners=https://0.0.0.0:443
  ssl.keystore.location=/home/ubuntu/cerf/kafka.server.keystore.jks
  ssl.truststore.location=/home/ubuntu/cerf/kafka.server.truststore.jks![Uploading image.png…]()

I generated the keystore and truststore following the instructions here "http://docs.confluent.io/3.0.0/kafka/ssl.html".
I visited the server via address like "https://[ip]" but found unaccessible. I set log level to "DEBUG" and found messages like below(failed to upload image, paste text here):

> [2016-07-29 04:41:27,335] DEBUG SslConnection@7a334003{NEED_WRAP,eio=-1/-1,di=-1} -> HttpConnect     ion@3cba87f2{FILLING} fill exit (org.eclipse.jetty.io.ssl.SslConnection:682)
2949 [2016-07-29 04:41:27,335] DEBUG  (org.eclipse.jetty.server.HttpConnection:275)
2950 javax.net.ssl.SSLHandshakeException: no cipher suites in common
2951         at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1348)
2952         at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:519)
2953         at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:799)
2954         at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:767)
2955         at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
2956         at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:516)
2957         at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:239)
2958         at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
2959         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
2960         at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
2961         at java.lang.Thread.run(Thread.java:745)
2962 Caused by: javax.net.ssl.SSLHandshakeException: no cipher suites in common
2963         at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
2964         at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1650)
2965         at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:281)
2966         at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:269)
2967         at sun.security.ssl.ServerHandshaker.chooseCipherSuite(ServerHandshaker.java:968)
2968         at sun.security.ssl.ServerHandshaker.clientHello(ServerHandshaker.java:682)
2969         at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:221)
2970         at sun.security.ssl.Handshaker.processLoop(Handshaker.java:913)
2971         at sun.security.ssl.Handshaker$1.run(Handshaker.java:853)
2972         at sun.security.ssl.Handshaker$1.run(Handshaker.java:851)
2973         at java.security.AccessController.doPrivileged(Native Method)
2974         at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1285)
2975         at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:612)
2976         ... 5 more
2977 [2016-07-29 04:41:27,336] DEBUG onClose DecryptedEndPoint@50183c42{/223.255.241.120:63555<->443,     CLOSED,ISHUT,OSHUT,-,-,5/30000,HttpConnection}->NetworkTrafficSelectChannelEndPoint@4bb4e0e2{/22     3.255.241.120:63555<->443,CLOSED,ISHUT,OSHUT,-,-,3/30000,SslConnection}{io=0,kio=-1,kro=-1} (org     .eclipse.jetty.io.AbstractEndPoint:108)

Anyone has some suggestions on this?

**Comment by ewencp** [comment]
@robinmisfit The error in the stacktrace seems to indicate the problem is that there are no cipher suites in common:

> Caused by: javax.net.ssl.SSLHandshakeException: no cipher suites in common

You can set `ssl.cipher.suites` in your config if the defaults that Jetty don't have any matches with the ones your client is using.
