### ISSUE TITLE
Allow for GZIP or other compressions on the http side

### ISSUE THREAD

**Issue by imdark** [confluentinc/kafka-rest#249]
we can specify compression on the producer/consumer to broker side but not the rest client to rest broker side.
probably using an http handler, https://netty.io/4.0/api/io/netty/handler/codec/compression/package-summary.html

**Comment by blootsvoets** [comment]
+1. Preferably, the REST Proxy would transparently handle the `Content-Encoding` header.

**Comment by ewencp** [comment]
This has been addressed in confluentinc/rest-utils#52 and will be available in the next CP release.

**Comment by blootsvoets** [comment]
Do I understand correctly from confluentinc/rest-utils#52, that it compresses responses from the server to the client, but does not handle compressed requests? The requests we send to topics are typically large (with a large number of records), whereas the response is <100 chars. So we'd probably need the reverse. Should I open an issue at confluentinc/rest-utils instead?
