### ISSUE TITLE
Crashes with Illegal Character (Producer)

### ISSUE THREAD

**Issue by whithajess** [confluentinc/kafka-rest#252]
Im seeing pretty consistent crashes with certain messages: (I have a round robin and it crashes all machines)

```
WARN Illegal character 0x0 in state=START for buffer 
WARN badMessage: 400 Illegal character 0x0 for HttpChannelOverHttp@3a3c2e5f{r=0,c=false,a=IDLE,uri=-} (org.eclipse.jetty.http.HttpParser:1344)
HeapByteBuffer@40e111d5[p=1,l=7361,c=16384,r=7360]={\x00<<<\x00\x04C\x00\x00\x00\x02\x00\x00I\xC9\x00\REDACTED}}}
>>>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00} (org.eclipse.jetty.http.HttpParser:1719)
Uncaught exception in kafka-producer-network-thread | producer-1:  (org.apache.kafka.common.utils.KafkaThread:30)
java.lang.OutOfMemoryError: Java heap space
```

I thought this could be just a java configuration thing but I am using the suggested tuning from the docs:
```
-Xms1g -Xmx1g -XX:PermSize=48m -XX:MaxPermSize=48m -XX:+UseG1GC -XX:MaxGCPauseMillis=20 \
       -XX:InitiatingHeapOccupancyPercent=35
```

I have built the proxy from source according to the docs and using:
```
java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
```

The other problem I have is I am doing a health check based on `/` and it still responds 200 after this crash but it does not send `POST` after the crash.

**Comment by armaseg** [comment]
Have you tried using the JDK 1.7 u51 

> We recommend running JDK 1.7 u51, and using the G1 collector. If you do this (and we highly recommend it), make sure you’re on u51. We tried out u21 in testing, but we had a number of problems with the GC implementation in that version. 
http://docs.confluent.io/2.0.0/kafka-rest/docs/deployment.html

**Comment by ewencp** [comment]
@whithajess Have you customized any of the producer settings? Can you get a stack trace and/or heap dump from the OOM error? It looks like the producer is simply running out of memory, but its memory usage should be pretty well bounded since it has limited buffer sizes. But if something else in the proxy is eating up memory, it could just be coincidence that the producer thread is the one that crashes.

And of course, there's the obvious question -- does increasing the max heap help? Even with the recommended settings, we can't guarantee the amount of memory used. For example, you can instantiate as many consumers as you want, each of which may have buffered data, so there can't be a strict upper bound on memory usage.

**Comment by whithajess** [comment]
@ewencp There was no consumers, just a producer and a reasonably low message rate I assumed that the memory was kind of overkill to be honest.

**Comment by jomach** [comment]
I'm hitting the same problem on a Kerberos Kafka Cluster when connecting Kafka-proxy to Kafka...
`2017-10-02 07:19:51 ERROR KafkaThread:43 - Uncaught exception in kafka-producer-network-thread | producer-2:
java.lang.OutOfMemoryError: Java heap space
	at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57)
	at java.nio.ByteBuffer.allocate(ByteBuffer.java:335)
	at org.apache.kafka.common.network.NetworkReceive.readFromReadableChannel(NetworkReceive.java:97)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:75)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.receiveResponseOrToken(SaslClientAuthenticator.java:244)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.authenticate(SaslClientAuthenticator.java:168)
	at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:76)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:376)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:326)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:433)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:224)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:162)
	at java.lang.Thread.run(Thread.java:748)
2017-10-02 07:19:56 DEBUG ClientCnxn:742 - Got ping response for sessionid: 0x25e9993a7875e0b after 0ms`

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

@whithajess where did you configure your jvm parameters ?

**Comment by shubhwip** [comment]
@whithajess I am facing the same issue How did you resolve the issue then?

**Comment by whithajess** [comment]
Stopped using kakfa rest we needed to have something reliable have found that the standard kafka java producer does not fall over like this.

**Comment by jomach** [comment]
If I remember correctly I was using 3.3.0 and my brokers were not compatible with it.

**Comment by whithajess** [comment]
Closing - stopped using as to fragile for production use in the state it was at the time.
