### ISSUE TITLE
Update doc for schema.registry.url

### ISSUE THREAD

**Issue by simplesteph** [confluentinc/kafka-rest#257]
According to this issue https://github.com/confluentinc/kafka-rest/issues/71 (which I think should be closed, see related issues and PR https://github.com/confluentinc/schema-registry/pull/184), a list of url is now authorized. This is not reflected in the documentation here: http://docs.confluent.io/3.1.1/kafka-rest/docs/config.html

```
schema.registry.url
The base URL for the schema registry that should be used by the Avro serializer.

Type: string
Default: “http://localhost:8081“
Importance: high
```

**Comment by simplesteph** [comment]
Sorry, it seems the issue still isn't actually solved

**Comment by ewencp** [comment]
@simplesteph Are you saying the multiple URL problem isn't solved or the docs?

**Comment by simplesteph** [comment]
Just the doc I guess, right? It doesn't say it's a list. If that's the case it needs to be updated (and it's great news)

**Comment by saito96** [comment]
schema.registry.url="list of url"?
Can anyone answer for me: Is that above have enable in latest confluent version (5.0.0)?
