### ISSUE TITLE
Kafka Rest, can it work with a Kafka Kerberoized cluster?

### ISSUE THREAD

**Issue by bharatviswa504** [confluentinc/kafka-rest#259]
Hi,
I have a question here.
1, Can kafka rest work with a kafka kerberoized cluster.
2. Does Kafka rest support any authentication, it supports only SSL according to documentation.

**Comment by ewencp** [comment]
1. The producer can work with Kerberos, but currently the consumer APIs still use the old consumer which does not support security. There is active work to move to the new consumer so security can be enabled for all the APIs.
2. The REST proxy gets authentication support via [rest-utils](https://github.com/confluentinc/rest-utils). Currently SSL and SASL (via HTTP Basic auth) are supported.

**Comment by bharatviswa504** [comment]
@ewencp Could you please provide more info 2nd point, how to setup authentication via SASL,

Because in configs, only SSL properties are only provided.
https://github.com/confluentinc/kafka-rest/blob/master/docs/config.rst

**Comment by ewencp** [comment]
@bharatviswa504 Sorry, I was thinking of the connection to Kafka -- rest-utils does, as you point out, only provide HTTPS support currently.
