### ISSUE TITLE
complie with apache kafka

### ISSUE THREAD

**Issue by bastianvs** [confluentinc/kafka-rest#266]
Can we use rest api feature with Apache version of kafka.  ?

**Comment by ewencp** [comment]
@bastianvs Sure, Confluent only distributes it with our build of Kafka but we do all development for Kafka in the Apache project so patches will land there. We only provide different version numbers to handle the case where we may fix a bug and have it committed to AK, but it has not yet been released by the Apache project.

You can simply adjust the version number of the dependency to get a version compiled against the Apache release of Kafka.
