### ISSUE TITLE
Unable to add values to union schema

### ISSUE THREAD

**Issue by ronaklotia** [confluentinc/kafka-rest#309]
I am fairly new to Avro and going through documentation for union schema. I have the example below where I have defined a Avro schema for Shape and a schema for Circle and Circle has reference to Shape

[
  {
    "namespace": "com.test",
    "type": "record",
    "name": "Shape",
    "fields": [
      {
        "name": "colour",
        "type": "string"
      }
    ]
  },
  {
    "namespace": "com.test",
    "type": "record",
    "name": "Circle",
    "fields": [
      {
        "name": "radius",
        "type": "int"
      },
      {
        "name": "super",
        "type": "com.test.Shape"
      }
    ]
  }
]

Using following curl command to create a Schema 
curl -X POST -H "Content-Type: application/vnd.schemaregistry.v1+json" \
     --data '{"schema":"[{\"namespace\":\"com.test\",\"type\":\"record\",\"name\":\"Shape\",\"fields\":[{\"name\":\"colour\",\"type\":\"string\"}]},{\"namespace\":\"com.test\",\"type\":\"record\",\"name\":\"Circle\",\"fields\":[{\"name\":\"radius\",\"type\":\"int\"},{\"name\":\"super\",\"type\":\"com.test.Shape\"}]}]"}' \
     http://localhost:8081/subjects/shapes/versions 

When I try to put some data I get an error "{"error_code":42203,"message":"Conversion of JSON to Avro failed: Failed to convert JSON to Avro: Expected field name not found: colour"}"

Using following command to add data in the shape topic

curl -X POST -H "Content-Type: application/vnd.kafka.avro.v2+json"       -H "Accept: application/vnd.kafka.v2+json"       --data '{"value_schema_id":469, "records": [{"value": {"com.test.Circle":{"radius":10,"super":{"com.test.Shape":{"colour":"blue"}}}}}]}'       "http://localhost:8082/topics/shape"

Can some one point out what if there is any mistakes in the format or something I am missing about JSON encoding here?

**Comment by mageshn** [comment]
@ronaklotia as i mentioned in SR issue https://github.com/confluentinc/schema-registry/issues/554 the message format doesn't comply to the schema
