### ISSUE TITLE
How do I add a custom Servlet Filter?

### ISSUE THREAD

**Issue by rangwea** [confluentinc/kafka-rest#312]
I want to add a custom Servlet Filter, but the "Application.class" can't modify. How do I?

**Comment by mageshn** [comment]
You would be able to do so after release 3.3. You would be able to add your own implementation of RestResourceExtension using which you can add Jersey Filters.

**Comment by ewencp** [comment]
Closing since the question has been answered, @rangwea feel free to reopen if you need some more guidance on this.
