### ISSUE TITLE
Get messages from topics - Seems count does not work ?

### ISSUE THREAD

**Issue by nsteinmetz** [confluentinc/kafka-rest#318]
Hi,

We have some PHP scripts that consume kafka messages via the REST API. We  use this method so far as our PHP scripts requires some heavy processing (not due to the message itself but for the actions after having parsed the message).

So we use : http://docs.confluent.io/current/kafka-rest/docs/api.html#get--topics-(string-topic_name)-partitions-(int-partition_id)-messages?offset=(int)[&count=(int)]

But when we specify `count`, it is ignored.  `òffset` works well but not `count`.

From my understanding, using this REST approach, we de not need to set up a consumer or should we ?

Thanks,
Nicolas

**Comment by ewencp** [comment]
@nsteinmetz Can you give more details on how you're making the request? I just did a simple test with `curl` like this:

```
curl "http://localhost:8082/topics/jsontest/partitions/0/messages?offset=0&count=2"
```

after having run a few steps from the quickstart and it seems to be working fine. If you were doing this from the shell I'd say you need to be careful about quoting the URL since the `&` would background the process without it, but I wouldn't expect that to be an issue from PHP.

**Comment by nsteinmetz** [comment]
Hi @ewencp,

I tested it in Chrome with the restlet plugin, so it's like a curl I think at the end. I forgot to mention we are in a bluemix (IBM cloud) context and as their doc refers to confluent one, there shouldn't be differences with a vanillia one - I hope so :)

My url is basically the same as yours : `https://<bluemix kafka rest endpoint>/topics/<mytopic>/partitions/0/messages?offset=0&count=2`. Will investigate further today...

Thanks for your feedback,
Nicolas

**Comment by nsteinmetz** [comment]
What i have:
`
URL: https://<bluemix endpoint>/topics/<topic>/partitions/0/messages?count=1

````
[
{"key":null,"value":"...","partition":0,"offset":0},
{"key":null,"value":"...","partition":0,"offset":1},
{"key":null,"value":"...","partition":0,"offset":2}
]
```

Hope it helps,
Nicolas

**Comment by ewencp** [comment]
I'm guessing logs aren't available from Bluemix? Unfortunately it will be difficult to find the issue. I'd suggest also testing from the command line -- I know folks have had some problems with the behavior of various browser extensions for testing REST APIs, and we know the curl command should work fine, so it'd be good to test a setup that we know works correctly.

**Comment by nsteinmetz** [comment]
Hi @ewencp,

Indeed I have no logs, will close the bug here and see if I can get some info from the Bluemix support team. Thanks for your help, will retry with curl after my summer break.

Nicolas
