### ISSUE TITLE
Is offsetsForTimes is available with kafka rest ?

### ISSUE THREAD

**Issue by Elyahou** [confluentinc/kafka-rest#319]
Can be used to rewind a consumer to a specific time

**Comment by ewencp** [comment]
@Elyahou At the moment that functionality is not provided. We added support for the new consumer API in v2 of the API in 3.2, but have not yet added support for `offsetsForTimes`.

**Comment by BeccaLiu** [comment]
Any updates for this feature in the latest version? or when you guys plan to release it?

**Comment by abhi-dnyate** [comment]
Is it available in latest version or planned for any yet to be released versions ?

**Comment by rigelbm** [comment]
This feature is part of the Confluent Platform 5.4 release.

Branch: https://github.com/confluentinc/kafka-rest/commits/5.4.x
PR: https://github.com/confluentinc/kafka-rest/pull/587

**Comment by abhi-dnyate** [comment]
Thanks for the reply, is it listed under, 

https://docs.confluent.io/current/kafka-rest/api.html ?
I couldn't find one or I may have missed ?

Could you post a sample query if it is not documented ?

**Comment by abhi-dnyate** [comment]
Thanks for reply, I could see the new API but couldn't make to work.
I have opened a new issue #615
