### ISSUE TITLE
kafka rest proxy duplicate messages on topic with cleanup policy compact

### ISSUE THREAD

**Issue by oleg-v-** [confluentinc/kafka-rest#321]
Hello! We use kafka and kafka rest proxy, also we have a topic with cleanup policy - a compact. If we read the messages by native java Kafka client, everything is fine, but if we make a request through the kafka rest proxy with a count parameter for example 100, then in about 69 messages returned, the Kafka Rest overwrites the actual response messages, those already present in the response, i.e. Offsets are duplicated

**Comment by oleg-v-** [comment]
We use 3.0.0 kafka rest version

**Comment by mageshn** [comment]
@oleg-v- internally kafka rest uses native client. With compacting enabled, you could get duplicate messages even in native client. If the compaction thread has not picked your segment yet, this is bound to happen. Also, you can use the V2 version of consumer API which uses the new consumer API and highly performant than the old consumer.

**Comment by mageshn** [comment]
I'm closing this issue , please feel free to open it if you are not satisfied.

**Comment by oleg-v-** [comment]
Well, why do I get different results by reading the topic through the rest and reading through the native client?
And why the result given by the rest is affected by the count, with different coun for the same offsets, different messages are returned.
