### ISSUE TITLE
cannot execute an mvn clean

### ISSUE THREAD

**Issue by bruciebruce** [confluentinc/kafka-rest#326]
downloaded zip file for this project today and ran an mvn clean on it.

---- start of output ----
root@bruce-VirtualBox:/devel/kafka-rest-master# mvn clean
[INFO] Scanning for projects...
[WARNING] Could not transfer metadata io.confluent:rest-utils-parent:3.5.0-SNAPSHOT/maven-metadata.xml from/to confluent (${confluent.maven.repo}): Cannot access ${confluent.maven.repo} with type default using the available connector factories: BasicRepositoryConnectorFactory
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for io.confluent:kafka-rest:[unknown-version]: Could not transfer artifact io.confluent:rest-utils-parent:pom:3.5.0-SNAPSHOT from/to confluent (${confluent.maven.repo}): Cannot access ${confluent.maven.repo} with type default using the available connector factories: BasicRepositoryConnectorFactory and 'parent.relativePath' points at wrong local POM @ line 7, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project io.confluent:kafka-rest:[unknown-version] (/devel/kafka-rest-master/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for io.confluent:kafka-rest:[unknown-version]: Could not transfer artifact io.confluent:rest-utils-parent:pom:3.5.0-SNAPSHOT from/to confluent (${confluent.maven.repo}): Cannot access ${confluent.maven.repo} with type default using the available connector factories: BasicRepositoryConnectorFactory and 'parent.relativePath' points at wrong local POM @ line 7, column 13: Cannot access ${confluent.maven.repo} using the registered transporter factories: WagonTransporterFactory: Unsupported transport protocol -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

---- end of output ----

**Comment by ewencp** [comment]
@bruciebruce You'll need to build some dependencies to be able to build a SNAPSHOT version of this repo. See this [FAQ](https://github.com/confluentinc/kafka-rest/wiki/FAQ#when-i-try-to-compile-i-get-an-error-about-a-missing-snapshot-dependency) for details (or build from a tagged release version).

**Comment by bruciebruce** [comment]
I am not getting this.  Am I supposed to resolve all maven <parent>...</parent> dependencies myself?
I tried to build 2 of the tagged versions and I see that they both have <parent> tags in them, so these have the same issue.  I am looking for a pom file that resolves all dependencies because all dependencies are listed in *that* pom file.  Can I do this?
