### ISSUE TITLE
unable to set listeners=http://0.0.0.0:80 

### ISSUE THREAD

**Issue by jmarcos-cano** [confluentinc/kafka-rest#338]
Whenever I set listeners to:  `listeners=http://0.0.0.0:80 ` I got a permission denied, there's nothing else listening on port 80 is there any other setting I need in order to make kafka-rest listen on port 80? 

Error thrown: 
```
WARN FAILED io.confluent.rest.Application$1@615091b8: java.net.SocketException: Permission denied (org.eclipse.jetty.util.component.AbstractLifeCycle:212)
java.net.SocketException: Permission denied
```

**Comment by treziac** [comment]
On Unix base system, ports below 1024 have restricted permissions, you should use iptable or other mean to redirect the port
See http://www.eclipse.org/jetty/documentation/current/setting-port80-access.html

**Comment by ewencp** [comment]
@treziac is correct, you'll need to provide permissions to bind to that port for the user you are starting the REST proxy with.
