### ISSUE TITLE
Do you plan to support GRPC

### ISSUE THREAD

**Issue by nikhil-dhiman** [confluentinc/kafka-rest#340]
In today's word, speed is what we all need. GRPC is way more speedier than HTTP rest call.

**Comment by mageshn** [comment]
@nikhil-dhiman Thanks for your suggestion but there is no immediate plans to support GRPC for Rest Proxy. HTTP rest call has wider coverage at the moment .

**Comment by huizhilu** [comment]
@mageshn Is it possible to reuse the existing code and convert kafka-rest to a grpc server with some work, or we have to create a grpc proxy and call the external kafka-rest from inside the grpc proxy?
