### ISSUE TITLE
Register active REST Servers with Zookeeper

### ISSUE THREAD

**Issue by rmkellogg** [confluentinc/kafka-rest#342]
To support automatic load balancing and fail-over with Apache Knox and other clients, it would be beneficial if the REST Proxy could optionally register live nodes of itself in Zookeeper.  

The Apache Curator Service Discovery (http://curator.apache.org/) module would be helpful during implementation of this new feature.

**Comment by mageshn** [comment]
@rmkellogg we are actually working on making RestProxy talk only to Kafka as part of our improvements. Also, everyone has different needs in terms of service discovery and orchestration. So, it would be best to implement something like that outside of RestProxy itself. If you would still want to extend restProxy to do something like that. You can try to implement your extension 

kafka.rest.resource.extension.class
Fully qualified class name of a valid Implementation of the interface RestResourceExtension. This can be used to inject user defined resources like filters. Typically used to add custom capability like logging, security, etc

**Comment by mageshn** [comment]
@rmkellogg I hope the above comment would have helped you. Im closing the issue and please feel free to open if you are not satisfied.
