### ISSUE TITLE
Scheme Registry failed to start 

### ISSUE THREAD

**Issue by vehbiakdogan** [confluentinc/kafka-rest#369]
Scheme registry failed to start help me plase 

root@km33501-01:/opt/confluent-4.0.0# confluent start
Starting zookeeper
zookeeper is [UP]
Starting kafka
kafka is [UP]
Starting schema-registry
|Schema Registry failed to start
schema-registry is [DOWN]
Starting kafka-rest
kafka-rest is [UP]
Starting connect
//opt/confluent-4.0.0/bin/confluent: line 230: 25173 Killed                  ${start_command} "${service_dir}/${service}.properties" 2> "${service_dir}/${service}.stderr" > "${service_dir}/${service}.stdout"
connect is [UP]

Configuration: 
- zookeeper

host.name=87.118.114.103
#port=2282
clientPort=2282
#disable the per-ip limit on the number of connections since this is a non-production config
maxClientCnxns=1

- scheme registry 

listeners=http://87.118.114.103:8081
kafkastore.connection.url=87.118.114.103:2282
kafkastore.topic=_schemas
debug=false

**Comment by cricket007** [comment]
Error is unrelated to the REST proxy, which itself started fine.

https://github.com/confluentinc/schema-registry/issues

**Comment by axisc** [comment]
Closing since this is unrelated to REST Proxy.
