### ISSUE TITLE
Can not start kafka-rest service for 4.0.0.

### ISSUE THREAD

**Issue by haiyangu** [confluentinc/kafka-rest#380]
I can't start kafka-rest service 4.0.0. But can start 3.3.0 successfully.
# rpm -qa |grep confluent
confluent-rest-utils-4.0.0-1.noarch
confluent-kafka-2.11-0.11.0.0-1.noarch
confluent-common-4.0.0-1.noarch
confluent-schema-registry-4.0.0-1.noarch
# netstat -ntpl
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      1/systemd           
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      28791/nginx: master 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      2140/sshd           
tcp        0      0 135.251.108.55:8665     0.0.0.0:*               LISTEN      25487/java          
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      2013/master         
tcp        0      0 135.251.108.55:8666     0.0.0.0:*               LISTEN      25487/java          
tcp        0      0 0.0.0.0:43712           0.0.0.0:*               LISTEN      25487/java          
tcp        0      0 127.0.0.1:9990          0.0.0.0:*               LISTEN      25487/java          
tcp6       0      0 :::35338                :::*                    LISTEN      6672/java           
tcp6       0      0 :::39115                :::*                    LISTEN      4252/java           
tcp6       0      0 :::111                  :::*                    LISTEN      1/systemd           
tcp6       0      0 :::22                   :::*                    LISTEN      2140/sshd           
tcp6       0      0 ::1:25                  :::*                    LISTEN      2013/master         
tcp6       0      0 :::9092                 :::*                    LISTEN      6672/java           
tcp6       0      0 :::2181                 :::*                    LISTEN      4252/java
# kafka-rest-start
[2018-01-04 18:36:39,077] INFO KafkaRestConfig values: 
	metric.reporters = []
	client.security.protocol = PLAINTEXT
	bootstrap.servers = 
	response.mediatype.default = application/vnd.kafka.v1+json
	authentication.realm = 
	ssl.keystore.type = JKS
	metrics.jmx.prefix = kafka.rest
	ssl.truststore.password = [hidden]
	id = 
	host.name = 
	consumer.request.max.bytes = 67108864
	client.ssl.truststore.location = 
	ssl.endpoint.identification.algorithm = 
	compression.enable = false
	client.zk.session.timeout.ms = 30000
	client.ssl.keystore.type = JKS
	client.ssl.cipher.suites = 
	client.ssl.keymanager.algorithm = SunX509
	client.ssl.protocol = TLS
	response.mediatype.preferred = [application/vnd.kafka.v1+json, application/vnd.kafka+json, application/json]
	client.sasl.kerberos.ticket.renew.window.factor = 0.8
	ssl.truststore.type = JKS
	consumer.iterator.backoff.ms = 50
	access.control.allow.origin = 
	ssl.truststore.location = 
	ssl.keystore.password = [hidden]
	zookeeper.connect = 
	port = 8082
	client.ssl.keystore.password = [hidden]
	client.ssl.provider = 
	client.init.timeout.ms = 60000
	simpleconsumer.pool.size.max = 25
	simpleconsumer.pool.timeout.ms = 1000
	ssl.client.auth = false
	consumer.iterator.timeout.ms = 1
	client.sasl.kerberos.service.name = 
	ssl.trustmanager.algorithm = 
	authentication.method = NONE
	schema.registry.url = http://localhost:8081
	client.ssl.truststore.type = JKS
	request.logger.name = io.confluent.rest-utils.requests
	ssl.key.password = [hidden]
	client.sasl.kerberos.ticket.renew.jitter = 0.05
	client.ssl.endpoint.identification.algorithm = 
	authentication.roles = [*]
	client.ssl.trustmanager.algorithm = PKIX
	metrics.num.samples = 2
	consumer.threads = 1
	ssl.protocol = TLS
	client.ssl.keystore.location = 
	debug = false
	listeners = []
	ssl.provider = 
	ssl.enabled.protocols = []
	client.sasl.kerberos.min.time.before.relogin = 60000
	producer.threads = 5
	shutdown.graceful.ms = 1000
	ssl.keystore.location = 
	consumer.request.timeout.ms = 1000
	ssl.cipher.suites = []
	client.timeout.ms = 500
	consumer.instance.timeout.ms = 300000
	client.sasl.kerberos.kinit.cmd = /usr/bin/kinit
	client.ssl.key.password = [hidden]
	access.control.allow.methods = 
	ssl.keymanager.algorithm = 
	metrics.sample.window.ms = 30000
	client.ssl.truststore.password = [hidden]
	client.ssl.enabled.protocols = TLSv1.2,TLSv1.1,TLSv1
	kafka.rest.resource.extension.class = 
	client.sasl.mechanism = GSSAPI
 (io.confluent.kafkarest.KafkaRestConfig:175)
[2018-01-04 18:36:39,127] INFO Logging initialized @1209ms (org.eclipse.jetty.util.log:186)
[2018-01-04 18:36:39,355] ERROR Server died unexpectedly:  (io.confluent.kafkarest.KafkaRestMain:63)
java.lang.RuntimeException: Atleast one of bootstrap.servers or zookeeper.connect needs to be configured
	at io.confluent.kafkarest.KafkaRestApplication.setupInjectedResources(KafkaRestApplication.java:104)
	at io.confluent.kafkarest.KafkaRestApplication.setupResources(KafkaRestApplication.java:83)
	at io.confluent.kafkarest.KafkaRestApplication.setupResources(KafkaRestApplication.java:45)
	at io.confluent.rest.Application.createServer(Application.java:157)
	at io.confluent.rest.Application.start(Application.java:495)
	at io.confluent.kafkarest.KafkaRestMain.main(KafkaRestMain.java:56)

**Comment by cricket007** [comment]
`Atleast one of bootstrap.servers or zookeeper.connect needs to be configured`

In the output you gave, both are blank. 

Your 3.3.0 configurations are not used by the 4.0.0 installation

**Comment by haiyangu** [comment]
I have tried and it works, thanks so much!

**Comment by cricket007** [comment]
Glad to hear. Feel free to close this issue
