### ISSUE TITLE
The consumer created by kafka-rest will be deleted automatically after some moment

### ISSUE THREAD

**Issue by haiyangu** [confluentinc/kafka-rest#392]
Hi,
I create a consumer with 
curl -X POST "http://kafka-rest-server:8082/consumers/testgroup" -H "accept: application/vnd.kafka.v1+json" -H "Content-Type: application/json" -d "{ \"name\": \"consumer1\", \"format\": \"json\", \"auto.offset.reset\": \"largest\", \"auto.commit.enable\": \"true\"}"
{"instance_id":"consumer1","base_uri":"http://135.251.108.55:8082/consumers/testgroup/instances/consumer1"}

And consumer1 will be deleted after some time while I didn't do any delete operation.
curl -X GET "http://kafka-rest-server:8082/consumers/testgroup/instances/consumer1/topics/test?max_bytes=12334567" -H "accept: application/vnd.kafka.json.v1+json"
{"error_code":40403,"message":"Consumer instance not found."}

Another question, when the consumer is just created, when I use GET method to get messages from a topic, it always shows [].

**Comment by awartika** [comment]
This is due to consumer.instance.timeout.ms property which is set to 1000 ms by default. Try increasing it and you will not see the issue.

**Comment by haiyangu** [comment]
I have tried and it works, thanks so much!
