### ISSUE TITLE
Rebalancing Partitions Failing

### ISSUE THREAD

**Issue by pramodgudipati** [confluentinc/kafka-rest#396]
Rebalancing partitions is not working as expected when using REST proxy API. 

Steps:
1. create a topic and published few records into the topic,
2. created a consumer instance C0 and subscribed to the topic and consumed records successfully. Instance C0 continuously polls for records from that topic,
3. create another consumer instance C1 in same consumer group and subscribe to the same topic.
4. Now, when consume records request is sent using instance C1, both C0 and C1 consume operations get stuck.

I could see following DEBUG statement in REST Proxy logs:
"DEBUG Attempt to heartbeat failed for group grp7 since it is rebalancing."

After few mins, one of the instance gets all the records published meanwhile. Rebalancing didn't happen.

I am using default values for all the variables like session.timeout.ms, heartbeat, group.poll.max.timeout.ms, group.poll.min.timeout.ms. 

Rebalancing worked fine when I used Kafka API directly instead of REST Proxy.  AM I missing something here ? I tried this on 3.2.2 and 4.0 versions of REST Proxy.

**Comment by woodlee** [comment]
@pramodgudipati Spent all day dealing with the exact same issue and think I may have it figured out. What I write below still has a lot of guesswork in it--and clarifications are very welcome--but the solution is working for me at least:

By default, the REST proxy's `consumer.threads` property is set to `1`. These threads correspond (?) to the consumer instances that _Kafka_ sees. When you try to create multiple consumer instances through the API, the instances you are creating get round-robined across the number of consumer threads that are available. So, in any instance where you try to create more consumer instances than there are consumer threads, the identity of the consumer instance from Kafka's perspective will flip-flop as interleaved record `GET` requests come in, leading to very frequent rebalancing and grinding things to a halt. Of course this is particularly problematic when there's just one consumer thread!

I couldn't find documentation on this _anywhere_, and think some clarification is sorely needed. In general, I've had a hard time reasoning about the relationship between consumer instances as provided by the REST proxy and consumer instances as used by the proxy when interacting with Kafka. Some documentation to clarify that would be extremely valuable. Some of what I found on Confluent's site suggests that in the past the proxy may have been limited to only one consumer thread, but the current code seems to be designed to deal with more. Maybe docs just weren't updated whenever that change was made.

In my case, I was trying to run 4 consumer instances against a topic with 12 partitions. To be future-proof, I just went ahead and set the `consumer.threads` property to 12 (I'm actually running this in Kubernetes, so I did it by setting env var `KAFKA_REST_CONSUMER_THREADS` on the Docker container). With that done, everything is working normally. I presume in this setup that 4 of the 12 threads are each tied directly to one of my API-registered consumer instances, and the other 8 are idle.

**Comment by praveenkannan** [comment]
@woodlee I had the same issue earlier and decided to read [KafkaConsumerManager](https://github.com/confluentinc/kafka-rest/blob/master/kafka-rest/src/main/java/io/confluent/kafkarest/v2/KafkaConsumerManager.java) code.  I think your theory is right and I tried that with my local instance of Kafka and it work.  I am still trying to figure out if the behavior of REST changes if more than consumer groups(with different number of consumer instances) subscribe to the same topic.

This was very stressful as there is really no documentation about this. I posted in confluent slack channel and didn't get a response either. Thanks for your suggestion, I am unblocked for. However, if we can get anyone from Confluent speak for it, that would be more authentic.

**Comment by awartika** [comment]
I changed the consumer.threads to 12 in kafka-rest.properties and created 2 consumer instances in a group. However I do not see the partition rebalancing across the 2 instances.

**Comment by pdruley** [comment]
@woodlee @praveenkannan 
Does the following section from the Confluent configuration documentation answer and support your understanding of how using multiple consumer instances should work? For instance it would seem using "-1" would be better suited then hard coding a number higher then the current number of instances.

`consumer.threads:
The maximum number of threads to run consumer requests on. Note that this must be greater than the maximum number of consumers in a single consumer group. The sentinel value of -1 allows the number of threads to grow as needed to fulfill active consumer requests. Inactive threads will ultimately be stopped and cleaned up.`
Taking from: https://docs.confluent.io/current/kafka-rest/docs/config.html#general

**Comment by woodlee** [comment]
Yes, that does help, thanks @pdruley ! Due to the recent improvements in Confluent's C# library we actually wound up switching to consuming without the REST proxy so we haven't revisited the issue for a while, but I think that probably does explain the behavior we were seeing previously. Glad to see that in the docs.

**Comment by addisonhuddy** [comment]
Thanks for the feedback.  This issue is resolved as of version 4.1+.  https://github.com/confluentinc/kafka-rest/pull/466

Closing for now.  Please re-open if the issue persists.
