### ISSUE TITLE
Avro Schema "Subject" key and "version" in Kafka-REST  POST request

### ISSUE THREAD

**Issue by keyankay** [confluentinc/kafka-rest#424]
I have created a AVRO  schema using the schema registry. My use case is to populate data into the topic via the Kafka REST proxy interface. How do i post the JSON data using "subject"/"version" and a POST Kafka Proxy REST request  ?

Ex: I create a AVRO schema as follows

curl -X POST -H "Content-Type: application/vnd.schemaregistry.v1+json" --data '{"schema": "{\"type\": \"record\", \"name\": \"User\", \"fields\": [{\"name\": \"name\", \"type\": \"string\"}]}"}' http://localhost:8081/subjects/Kafka-value/versions

To add values in topic, i used the following command
curl -X POST -H "Content-Type: application/vnd.kafka.avro.v2+json" -H "Accept: application/vnd.kafka.v2+json" --data '{"value_schema_id": 61, "records": [{"value": {"name":"testUser"}}]}'  "http://localhost:8082/topics/avrotest"

However, in the above "value_schema_id" is used. I am looking for ways of providing "subject name" Ex: "Kafka-value" subject name for posting records

**Comment by caglarturkurka** [comment]
@keyankay Did you solve your problem ? Because I have same problem and I want to learn that how can I solve iy ?

**Comment by keyankay** [comment]
I did not find a solution for this. I shared the schema name to the Kafka REST producer and made it a two step process.
1. From the Schema name query the Value id from the Avro Schema registry, parse the response to query for the Value id.
2. Kafka REST Producer, sends REST messages with the returned value id.

**Comment by keyankay** [comment]
> I did not find a solution for this. I shared the schema name to the Kafka REST producer and made it a two step process.
> 
> 1. From the Schema name query the Value id from the Avro Schema registry and parse the response to retrieve the Value id.
> 2. Kafka REST Producer, sends REST messages with the returned value id.
