### ISSUE TITLE
Receiving 500 Internal Server Error during POST

### ISSUE THREAD

**Issue by sigmazen** [confluentinc/kafka-rest#430]
Hi
I'm new to Kafka and am following the online guides:
https://docs.confluent.io/5.0.0-beta1/ksql/docs/api.html
https://docs.confluent.io/5.0.0-beta1/kafka-rest/docs/intro.html

Everything is working well with the demos eg `ksql-datagen` but when I try POSTing per the kafka-rest guide I'm getting a 500 error.

The steps I've done is:
- Created a new `jsontest` topic
- Successfully retrieved details using:
`curl -X GET -H "Accept: application/vnd.kafka.v2+json" "http://localhost:8082/topics/jsontest"`

- Tried to POST a record but getting a 500 Internal Server Error
`curl -X POST -H "Content-Type: application/vnd.kafka.json.v2+json" \ 
            -H "Accept: application/vnd.kafka.v2+json" \ 
            --data '{"records":[{"value":{"foo":"bar"}}]}' "http://localhost:8082/topics/jsontest"`

and I'm using the v5.0.0-beta1 version.
Any guidance would be most appreciated.
Cheers
Simon

PS: I'm also having the same problem using `confluent-4.1.0`

**Comment by biswajit123** [comment]
Can you please share , how did you solve the problem?
