### ISSUE TITLE
/consumers returns 404 but consumer exists

### ISSUE THREAD

**Issue by glarus089** [confluentinc/kafka-rest#456]
Hi! 
We have 4.0.1 confluent distrib. and if I try to type
curl host:8082/topics, I get topics list, but if I try curl host:8082/consumers - HTTP 404 ERROR.
In the same time  / bin/kafka-consumer-groups returns info about currently working consumer group.

**Comment by stanislavkozlovski** [comment]
Hi @glarus089,

Thanks for the issue! The Kafka REST proxy does not expose a `GET /consumers` endpoint. Here is the API reference: https://docs.confluent.io/4.0.1/kafka-rest/docs/api.html
