### ISSUE TITLE
All string keys posted are quoted

### ISSUE THREAD

**Issue by ddseapy** [confluentinc/kafka-rest#465]
When doing a POST request data with something like the following:
```json
{"records":[{"key":"myKey1","value":{ ... }},{"key":"myKey2","value":{ ... }}]}
```
The resulting topic has quoted keys: "myKey1", "myKey2".

Is there any way to make the keys not quoted?  It's not valid json if removing the quotes in the request, so an internal server error gets thrown.

**Comment by stanislavkozlovski** [comment]
Hi @ddseapy 

There is no way to have the keys not be quoted.
It is arguably better off to have them quoted since the REST proxy supports JSON objects as keys. We then need to have strings quoted to differentiate them between actual objects.

**Comment by ddseapy** [comment]
@stanislavkozlovski Fair enough, i'll close this.  I just ended up using ksql to re-key them on another topic after ingest.
