### ISSUE TITLE
Committing offsets in String format returns 500

### ISSUE THREAD

**Issue by stanislavkozlovski** [confluentinc/kafka-rest#501]
While testing a feature through a crudely-written script, I found out that the proxy has an internal server error when you try to commit a string offset:
Payload:
```
{
"offsets": [{ "topic": "test-topic", "offset": "tank"}]
}
```

Ideally, it should return a 400 and not print a huge stack trace in the logs.

**Comment by stanislavkozlovski** [comment]
@muralimani you absolutely can! Go for it

**Comment by muralimani** [comment]
Hi Stanislavkozlovski, Can you please share the exception trace?

**Comment by stanislavkozlovski** [comment]
Sorry @muralimani , I don't have it anymore. You should read the rest proxy's documentation and spin a server up (with Kafka), so that you get acquainted to it. Then, you could reproduce the bug directly

**Comment by muralimani** [comment]
Hi Stanislav, I was able to replicate the issue with local setup. I am working on the code fix now.

**Comment by MarkC0x** [comment]
Hi @stanislavkozlovski, I stumbled upon this issue recently and noticed it still persists in the later versions of the Rest Proxy.  I have the environment and problem recreated, so if it's still useful, let me put together a quick PR to handle the exception and return the correct error code.

**Comment by stanislavkozlovski** [comment]
That would be amazing!
