### ISSUE TITLE
Add support for compression, other global producer configs

### ISSUE THREAD

**Issue by ewencp** [confluentinc/kafka-rest#51]
Settings like compression can probably be configured globally just by exposing the producer config option as one of the REST proxy's config options and passing it along to both the binary and avro producers. The implementation should be trivial; the primary question is how we want to expose these options, e.g. by prefixing all the producer options with "producer." and forwarding everything, by allowing options to pass-through if they aren't processed by the KafkaRestConfig, or maybe some other approach.

**Comment by marekstachura** [comment]
@ewencp I can't find the information what compression.type is used by default...
Can I specify the compression.type in Kafka REST config? If yes, what types are available?

Thanks,
Marek

**Comment by ewencp** [comment]
@marekstachura See the notes at the beginning of the [config docs](http://docs.confluent.io/2.0.1/kafka-rest/docs/config.html#configuration-options). You can pass in parameters to override producer/consumer settings in the REST proxy configuration. Otherwise, generally the defaults are the same as they are for the underlying Java clients.
