### ISSUE TITLE
How do we get JMX metrics data?

### ISSUE THREAD

**Issue by RoyalFeng** [confluentinc/kafka-rest#569]
I want to use custom jmx metrics, can someone tell me how to get JMX metrics data?

**Comment by RoyalFeng** [comment]
I can not find JMX port, so where can I set the port ?

**Comment by RoyalFeng** [comment]
@ewencp  Dear ewencp , can you help me solve this issue

**Comment by pecanNBU** [comment]
download jmx_prometheus_javaagent-0.11.0.jar, then set the kafka-rest-run-class，export the jmx_port and jmx_opts, finally restart you kafka-rest service

**Comment by RoyalFeng** [comment]
> download jmx_prometheus_javaagent-0.11.0.jar, then set the kafka-rest-run-class，export the jmx_port and jmx_opts, finally restart you kafka-rest service

Thank you, can i set jmx_port in code?

**Comment by rigelbm** [comment]
You need to set the `JMX_PORT` environment variable. See https://github.com/confluentinc/kafka-rest/blob/master/bin/kafka-rest-run-class#L53
