### ISSUE TITLE
can we use this for commercial

### ISSUE THREAD

**Issue by saneera** [confluentinc/kafka-rest#577]
can we use this for the commercial environment without licence

**Comment by TrueWill** [comment]
You probably want to review https://github.com/confluentinc/kafka-rest/blob/master/LICENSE with an attorney.

I am not an attorney, but it appears to depend on your purpose:

      For purposes of this Agreement, “Excluded Purpose” means making
      available any software-as-a-service, platform-as-a-service,
      infrastructure-as-a-service or other similar online service that competes
      with Confluent products or services that provide the Software.

**Comment by rigelbm** [comment]
See https://www.confluent.io/confluent-community-license-faq/.
