### ISSUE TITLE
Facing issues with mvn test (v5.3.0) failing in the first attempt

### ISSUE THREAD

**Issue by nerissad** [confluentinc/kafka-rest#578]
In this version, with the mvn multiple project structure, and mvn test at the parent level fails at kafka-rest with the following error,

[ERROR]   ConsumerResourceAvroTest.<init>:48->AbstractConsumerResourceTest.<init>:67 » NoClassDefFound
[ERROR]   ConsumerResourceBinaryTest.<init>:46->AbstractConsumerResourceTest.<init>:67 » NoClassDefFound
[ERROR]   ConsumerResourceTest.<init>:47->AbstractConsumerResourceTest.<init>:67 » NoClassDefFound
[ERROR]   ConsumerResourceTest.<init>:47->AbstractConsumerResourceTest.<init>:67 » NoClassDefFound
[ERROR]   ConsumerResourceTest.<init>:47->AbstractConsumerResourceTest.<init>:67 » NoClassDefFound
[ERROR]   ConsumerResourceTest.<init>:47->AbstractConsumerResourceTest.<init>:67 » NoClassDefFound
[ERROR]   ConsumerResourceTest.<init>:47->AbstractConsumerResourceTest.<init>:67 » NoClassDefFound
[ERROR]   PartitionsResourceAvroConsumeTest.<init>:38->PartitionsResourceAbstractConsumeTest.<init>:43 » NoClassDefFound
[ERROR]   PartitionsResourceBinaryConsumeTest.<init>:38->PartitionsResourceAbstractConsumeTest.<init>:43 » NoClassDefFound

However it passes when I try to continue the tests, without any changes
mvn -rf :kafka-rest

**Comment by 51n15t9r** [comment]
Same error in 5.3.1 branch too.

**Comment by rigelbm** [comment]
This error only affects running the test from the top level because the project used to use shading on one of the modules. When running everything together, mvn would get confused. Since v6.0.0 this is not the case anymore, as this module has been removed.
