### ISSUE TITLE
get all consumer consumers

### ISSUE THREAD

**Issue by dishytianxiang** [confluentinc/kafka-rest#583]
can i use api to get all consumer groups?

**Comment by dishytianxiang** [comment]
how can i use api to get all consumer consumers?

**Comment by grongor** [comment]
Not a maintainer, but ... Issues aren't for questions. Use google/stackoverflow/anyotherplatform for that. Or you can just consult the API docs https://docs.confluent.io/current/kafka-rest/api.html

**Comment by rigelbm** [comment]
An API has been added in Confluent Platform 6.0.0 (coming out soon!). You can find the specification here: https://github.com/confluentinc/kafka-rest/blob/6.0.x/api/v3/openapi.yaml#L284
