### ISSUE TITLE
The requested embedded data format does not match the deserializer for this consumer instance

### ISSUE THREAD

**Issue by lovelyplanet2019** [confluentinc/kafka-rest#590]
i am using Kafka rest and Postman to post/get the data from kafka. having problem at #4. anyone knows why, is that because of incorrect Content-Type set when send GET request?

1. Create new consumer group TC1, consumer instance my_consumer1 (works well)
POST
http://127.0.0.1:8082/consumers/TC1
Content-Type : application/vnd.kafka.v2+json

HTTP Body
{
  "name": "my_consumer1",
  "format": "json",
  "auto.offset.reset": "latest",
  "auto.commit.enable": "false"
}

2. Subscribe to the consumer group TC1, consumer instance my_consumer1, topic TestTopic1. Note the TestTopic1 is already exist in Kafka without assigned to any consumer before. (works well)
POST
http://127.0.0.1:8082/consumers/TC1/instances/my_consumer1/subscription
Content-Type : application/vnd.kafka.v2+json

HTTP Body
{
  "topics": [
    "TestTopic1"
  ]
}

3. to confimed TestTopic1 subscribed sucessfully (works well as response returned the correct topic name)
GET
http://127.0.0.1:8082/consumers/TC1/instances/my_consumer1/subscription
Content-Type : application/vnd.kafka.v2+json

4. Fetch data from TestTopic1 using the subscribe (this has problem)
http://127.0.0.1:8082/consumers/TC1/instances/my_consumer1/records
Content-Type : application/vnd.kafka.v2+json

{
    "error_code": 40601,
    "message": "The requested embedded data format does not match the deserializer for this consumer instance"
}

**Comment by lovelyplanet2019** [comment]
issue resolved by using content type binary v2

**Comment by vishwajeets7** [comment]
@lovelyplanet2019 
Facing the same issue, the only difference is in my example avro format is used. Not sure how to reference the schema url with the rest api. As well if you can provide more information on the content type used in your example.

Thanks in advance.

**Comment by MiguelMendozaMolina** [comment]
what you need is to be able to place the header of the json type as you can see in this example, all the other steps are correct thanks for info @lovelyplanet2019 
![image](https://user-images.githubusercontent.com/5330569/108425128-ce3fc780-7218-11eb-8c3f-8e881d4a81ec.png)
