### ISSUE TITLE
Rest Proxy API unauthorized when communicating to Schema Registry with Basic Auth

### ISSUE THREAD

**Issue by omnipresentminded** [confluentinc/kafka-rest#592]
When using the Rest Proxy API to consume records with avro format and the schema registry is secured with Basic Auth, the communication is unauthorized. 
The documentation for the Kafka Rest Proxy does not explain how to pass the username and password for schema registry.

For ksql, the documentation says:
```
ksql.schema.registry.basic.auth.credentials.source=USER_INFO
ksql.schema.registry.basic.auth.user.info=username:password
```
I am running this in docker and using the env variables 
`KAFKA_REST_SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO` and `KAFKA_REST_BASIC_AUTH_CREDENTIALS_SOURCE`

We could not find in the code where it was using basic auth when communicating with schema registry to find the settings that would need populated.

How do you allow Rest Proxy API to communicate with Basic Auth to schema registry, and could the documentation be updated to reflect the how?

**Comment by omnipresentminded** [comment]
I have discovered with the help of the confluent cloud all in one docker compose file that I should be using `KAFKA_REST_CLIENT_SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO` and `KAFKA_REST_CLIENT_BASIC_AUTH_CREDENTIALS_SOURCE' . It would be very helpful if the documentation mentioned how to do this like ksql's documentation does.

**Comment by StevoKe** [comment]
@omnipresentminded  Thanks, this was actually very helpful when connecting the proxy to Confluent Cloud.
I agree that a reference in the documentation would be helpful!
