### ISSUE TITLE
Request for consumer records hangs (consumer groups)

### ISSUE THREAD

**Issue by grongor** [confluentinc/kafka-rest#597]
I'm not entirely sure when exactly this happens but it definitely is when the newly created consumer doesn't have any partition assigned. For example after rebalancing when other processes crashed, or when the process itself crashed and was quickly re-run by supervisor, and there is no partition for it yet (dead-processes' consumer wasn't deleted and therefore still holds the partition, until timed out and cleaned).

However, when this happens, it further amplifies the problem, because the new consumer will timeout, which triggers yet another rebalance.

You can clearly see it in this screenshot from our logging system (we have instance timeout set to 1 minute):

![image](https://user-images.githubusercontent.com/972493/69334434-faa61600-0c5a-11ea-99a6-05caafe4ce1e.png)

It seems like a call for records waits for the old consumer to be cleaned up and only after that it sends the response, completely ignoring the request timeout parameter (and proxy config entry).

We have 3 proxies behind a load balancer, all configured identically.

**Comment by joaomatossilva** [comment]
I'm also having this behavior with a simple scenario. 
One topic with 2 particions. I spawn 2 consumer instances on the same resource group and they work well. 

The problem arises if one gets killed and thus not deleting the subscription and I try to restart it, not only the instance goes timeout without any response, but the one that was working fine also gets hang.
Only after the Consumer Instance timeout is reached, I'm able to resume.

Both consumers are supposed to be hosted inside containers, so we don't really have controll on how they are spawned or killed.

**Comment by swapnil1988** [comment]
Any update on this issue? I am also facing the same issue.

**Comment by grongor** [comment]
@rigelbm Hi, is this project dead or what? There are many relevant issues and basically no response from Confluent/any maintainer. This issue, in particular, blocks me from using the REST proxy.

**Comment by ehumber** [comment]
This should be fixed by https://github.com/confluentinc/kafka-rest/pull/942

Closing the issue. @grongor, please reopen if you still see the problem after the change in #942

**Comment by simPod** [comment]
@ehumber Hello! Based on staleness of this issue (that said critical functionality not being production ready for few years), we considered this project abandoned or rather just a prototype for hello world projects. Did you re-start active development   so it is safe to use?

**Comment by ehumber** [comment]
Hi @simPod  

Yes, it's very much alive!

**Comment by grongor** [comment]
> Yes, it's very much alive!

Hi, it's good to read this :slightly_smiling_face: I would just like to make sure that we understand each other: did you always consider it "very much alive" (because it wasn't, see this and basically every other issue as an example), or did something actually change and NOW we can consider it "very much alive"? To be blunt: I want to know if this is typical corporate "everything is fine", or if Confluent actually changed something (new hires, new priorities,...) and we can expect a brighter future. Thank you!

**Comment by axisc** [comment]
@grongor Thanks for raising the concerns and I'd like to express my gratitude for your interest and use of Kafka REST. I assure you that this project has never been abandoned and the team is invested in [making improvements to the stability, usability and the performance](https://github.com/confluentinc/kafka-rest/pulls?q=is%3Apr++) of Kafka REST.

Our community engagement through issues and discussions could definitely be better and we will take active steps to do that.
