### ISSUE TITLE
Issue getting messages by offset / timestamp

### ISSUE THREAD

**Issue by abhi-dnyate** [confluentinc/kafka-rest#615]
I am using confluent 5.4 , kafka 2.13-2.4.0

Trying to use, below endpoint API, to get messages after a certain timestamp (get first messages after xxx):
GET /topics/(string:topic_name)/partitions/(int:partition_id)/messages[?offset=(int)][&timestamp=(string)][&count=(int)]

1. Created a topic
2. Inserted few messages.

$ sh bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic kTopic --from-beginning --partition 0
{"key1":"val1"}
{"key1":"val2")
{"key1":"val3")
^CProcessed a total of 3 messages
 
3. Tried with the current timestamp=>
$ curl -X GET -H "Content-Type: application/vnd.kafka.v1+json" -H "Accept: application/vnd.kafka.v1+json"   "http://localhost:8082/topics/kTopic/partitions/0/messages?timestamp=2020-02-13T06:15:00Z"
{"error_code":50002,"message":"Kafka error: Can't perform operation without zookeeper connect details"} $ 

4. Tried using a old timestamp =>
$curl -X GET -H "Content-Type: application/vnd.kafka.v1+json" -H "Accept: application/vnd.kafka.v1+json"   "http://localhost:8082/topics/kTopic/partitions/0/messages?timestamp=2019-02-13T06:15:00Z"
{"error_code":50002,"message":"Kafka error: Can't perform operation without zookeeper connect details"}

5. Tried using offset=>
$curl -X GET -H "Content-Type: application/vnd.kafka.v1+json" -H "Accept: application/vnd.kafka.v1+json"   "http://localhost:8082/topics/kTopic/partitions/0/messages?offset=0"
{"error_code":50002,"message":"Kafka error: Can't perform operation without zookeeper connect details"}

6. Tried with future timestamp : it returns empty records (which is expected)=>
curl -X GET -H "Content-Type: application/vnd.kafka.v1+json" -H "Accept: application/vnd.kafka.v1+json"   "http://localhost:8082/topics/kTopic/partitions/0/messages?timestamp=2020-02-13T10:35:00Z"
[]

Is there any issue or am I using API incorrectly ?

**Comment by rigelbm** [comment]
"Kafka error: Can't perform operation without zookeeper connect details" means you need to set `zookeeper.connect` on your rest-proxy properties. That should be set to `host:port` of the Zookeeper instance used by Kafka. If you are using the Confluent docker image, you can set the environment variable `KAFKA_REST_ZOOKEEPER_CONNECT`.

**Comment by abhi-dnyate** [comment]
Enabled debug log and it is showing below exception for the requests for which there was the error.
I have specified the format as vnd.kafka.v1+json, not sure if should it call 
consumeBinary or consumeJson ?

```
[2020-02-13 17:32:54,006] ERROR Request Failed with exception  (io.confluent.rest.exceptions.DebuggableExceptionMapper)
io.confluent.rest.exceptions.RestServerErrorException: Kafka error: Can't perform operation without zookeeper connect details
	at io.confluent.kafkarest.Errors.kafkaErrorException(Errors.java:206)
	at io.confluent.kafkarest.SimpleConsumerManager.consume(SimpleConsumerManager.java:193)
	at io.confluent.kafkarest.resources.PartitionsResource.consume(PartitionsResource.java:261)
	at io.confluent.kafkarest.resources.PartitionsResource.consumeBinary(PartitionsResource.java:120)


```

**Comment by abhi-dnyate** [comment]
Thanks a lot, that worked, I am getting response now.
The value I am getting is encoded, 

$ sh bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic kTopic --from-beginning --partition 0
{"timestamp":"2020-02-13T10:24:00Z"}
{"timestamp":"2020-02-13T10:24:10Z"}
{"timestamp":"2020-02-13T10:24:15Z"}
^CProcessed a total of 3 messages


$ curl -X GET -H "Content-Type: application/vnd.kafka.v1+json" -H "Accept: application/vnd.kafka.v1+json"   "http://localhost:8082/topics/kTopic/partitions/0/messages?offset=0&count=10"
[{"topic":"kTopic","key":null,"value":"eyJ0aW1lc3RhbXAiOiIyMDIwLTAyLTEzVDEwOjI0OjAwWiJ9","partition":0,"offset":0},{"topic":"kTopic","key":null,"value":"eyJ0aW1lc3RhbXAiOiIyMDIwLTAyLTEzVDEwOjI0OjEwWiJ9","partition":0,"offset":1},{"topic":"kTopic","key":null,"value":"eyJ0aW1lc3RhbXAiOiIyMDIwLTAyLTEzVDEwOjI0OjE1WiJ9","partition":0,"offset":2}]

Is this expected ?

**Comment by rigelbm** [comment]
See my previous comment: https://github.com/confluentinc/kafka-rest/issues/615#issuecomment-585726125

**Comment by rigelbm** [comment]
When consuming, you should specify the message serialization format using the `Accept` header. Assuming your messages are serialized as JSON, that should be `application/vnd.kafka.json.v1+json`. See https://docs.confluent.io/current/kafka-rest/api.html#get--topics-(string-topic_name)-partitions-(int-partition_id)-messages[?offset=(int)][&timestamp=(string)][&count=(int)] for more details.

**Comment by abhi-dnyate** [comment]
Oh ok, got it. That resolved all the issues. Thanks a lot.
