### ISSUE TITLE
Consumer read request hangs if you try to create two consumer instances with the same ID

### ISSUE THREAD

**Issue by ewencp** [confluentinc/kafka-rest#65]
If you:
1. Create consumer with an ID
2. Read from a topic
3. Create consumer with same ID (don't delete previous one)
4. Read from topic
the second create call succeeds and the read hangs. The stack trace shows it stuck trying to create a zookeeper node in a method that can also handle conflicts, which we'd expect since the IDs are the same.

Turns out that we ended up conflating the meaning of "ID", which is used both to name the consumer nicely so you have readable consumer URLs and it got passed in as the ID for the underlying old Kafka consumer. The latter should really only be happening for debugging purposes since a random UUID (generated automatically for the consumer if the ID is omitted) is way more reliable.

Things get a bit more confusing when we consider moving to the new consumer, which has a separate client ID that it uses to make logging on the brokers clearer and traceable to specific applications.

A fix for this has to be careful about compatibility. I think the right thing to do is add a new parameter ("name") which will be used in the URL. If the "id" is specified and "name" isn't, "name" will default to "id". The underlying Kafka "consumer.id" will only be set if "id" was explicitly set. Then, the name is only relevant to the single instance of the REST proxy since consumer URLs are specific to a single process. We can return a 409 if we see a naming conflict during creation, which will prevent the subsequent hang during read. Finally, we'll want to deprecate and deemphasize the "id" field in the docs since "name" will now be the field they really should be using.

**Comment by cwscribner** [comment]
+1 to a 409 and "name" field for this.  Both I and my colleagues have run into this on a few occasions when getting people up to speed with Confluent.

My experience has been when creating two consumers with the same ID, it invalidates the ability to read from the given consumer.

1. Create consumer with an ID of 'my_consumer'
2. Read topic xyz // Success
3. Create consumer with an ID of 'my_consumer'
4. Read topic xyz // Fails with "Consumer instance not found"

**Comment by mikebridge** [comment]
It looks like the workaround for this in #67 is to auto-assign consumer ids, but in the case where someone recreates a consumer with the same group/id, it still hangs and corrupts the consumer proxy until it's deleted properly.  I think it would be less confusing if an attempt to create a duplicate client was either idempotent or threw an error.

I encountered this because I was trying to restart a failed consumer that didn't deregister correctly.  A clearer error would have made it a little easier to debug.

```bash
$ curl -X POST -H "Content-Type: application/vnd.kafka.v1+json" --data '{"format": "binary", "auto.offset.reset": "smallest", "id": "test123"}' http://localhost:8082/consumers/my_test_consumer
=> {"instance_id":"test123","base_uri":"http://localhost:8082/consumers/my_test_consumer/instances/test123"}

$ curl -X GET -H "Accept: application/vnd.kafka.binary.v1+json" http://localhost:8082/consumers/my_test_consumer/instances/test123/topics/test
=> // lots of data

$ curl -X POST -H "Content-Type: application/vnd.kafka.v1+json" --data '{"format": "binary", "auto.offset.reset": "smallest", "id": "test123"}' http://localhost:8082/consumers/my_test_consumer
=> {"instance_id":"test123","base_uri":"http://localhost:8082/consumers/my_test_consumer/instances/test123"}

$ curl -X GET -H "Accept: application/vnd.kafka.binary.v1+json" http://localhost:8082/consumers/my_test_consumer/instances/test123/topics/test
=> []

$ curl -X GET -H "Accept: application/vnd.kafka.binary.v1+json" http://localhost:8082/consumers/my_test_consumer/instances/test123/topics/test
=> {"error_code":40403,"message":"Consumer instance not found."}
```

**Comment by mikebridge** [comment]
... and it looks like there's no call to list the currently-registered consumer instances.  When I start my consumer, how can I check that there isn't already another (potentially zombie) consumer in the consumer group?

Currently it seems like I should avoid auto-assigning instanceids in case they get lost during a client crash, and then call DELETE on my self-allocated instanceid (in case it's already there) whenever I start my consumer up, is that correct?

**Comment by ewencp** [comment]
@mikebridge Are you definitely running with the latest code? The third request in your example gives me the following output, which is what is now expected when you provide a conflicting consumer ID.

```
{"error_code":40902,"message":"Consumer with specified consumer ID already exists in the specified consumer group."}
```

Note that in all of these examples, the group ID (corresponding to the Kafka consumer's `group.id`) is the same -- `my_test_consumer`. What changes is the consumer ID (which I like to refer to as *consumer instance ID* to make it clearer that it refers to one instance of a consumer class). The previous problem was that people would assign fixed IDs in their code, not always aware of what this setting meant to the underlying consumer group, and then hit this error where they would end up accidentally double registering. This is especially common if the process that created the first instance crashed and didn't have a chance to clean up by `DELETE`ing the instance.

Note that the default behavior for the Java Kafka consumer is to auto-assign an ID, which avoids conflicts when trying to register consumers as part of the group. In this case, we recommend using randomized IDs as well. You can still run into issues if you are using multiple REST proxy instances and try to use the same ID *across multiple instances*, since they cannot check with each other to avoid duplicates. The code as in trunk should handle the single-node case for you. Since we generally expect people will end up scaling their workload to multiple REST proxy instances, or even just have multiple for HA purposes, it is difficult to ensure correct behavior unless you guarantee certain consumers are always bound to the same instance (since a crash in your application followed by a  new instance recovering could result in duplicate consumers). But by doing that you'd give up the HA and some of the scalability benefits of spreading across multiple instances.

Ultimately, this is just a limitation of the way the REST proxy is implemented to work nicely with any HTTP library. The lack of an specific connection we can tie to the consumer instance limits how we can clean it up. So, based on the latest code, we'd recommend:
* Allow the proxy to auto-allocate a random ID to avoid conflicts.
* Record the info about the instance (i.e. it's URL prefix) when you get the initial response. You'll need this to read data anyway.
* If at all possible, cleanly `DELETE` the consumer instance if you are going to stop the process that created it. This includes trying to take care to delete it even in exceptional failure modes if possible (i.e. a top-level exception handler).
* Select your `consumer.instance.timeout.ms` setting carefully. Ideally crashing processes are not common; rebalances will occur and some partitions will remain unavailable during the timeout. However, after the timeout the consumer instance should be destroyed and those partitions will be redistributed. You can reduce this unavailability using the timeout setting, but the tradeoff is that if any processing takes too long, you might accidentally wait too long between requests and the consumer instance will be cleaned up before you wanted it to be. As always, it's a tradeoff and might be application-specific.
Note that we've also designed this to work behind load balancers, so the URLs you get back *are tied to the specific REST proxy instance holding the instance*. This ensures you can read from and delete consumer instances even if they were created by running a request through a load balancer.

**Comment by mikebridge** [comment]
@ewencp Thanks for the detailed response.  I was using whatever was bundled with Confluent 1.0 but I came back to this this week and found that upgrading 2.0 fixes the issue with the consumer instance hanging when I deregister incorrectly.

I'm a little intimidated with the details of writing a client that will scale out correctly when I have multiple nodes to draw from but this helps a lot with the details, thanks!
