### ISSUE TITLE
Inconsistent use of @Nullable

### ISSUE THREAD

**Issue by fantayeneh** [confluentinc/kafka-rest#661]
Just browsing the codebase,
there are few places where the same field is annotated with both `@NotNull and  @Nullable`

https://github.com/confluentinc/kafka-rest/blob/master/kafka-rest/src/main/java/io/confluent/kafkarest/entities/v3/UpdateBrokerConfigRequest.java#L31-L32

It is easy also to see in few places `@Nullable` fields are accessed without the proper check.

**Comment by rigelbm** [comment]
We have migrated these POJOs to use AutoValue + Optional. Thanks for reporting. :)
