### ISSUE TITLE
Document how to change broker/topic configuration programmatically

### ISSUE THREAD

**Issue by holgerbrandl** [confluentinc/kafka-rest#676]
Neither the repos README nor https://docs.confluent.io/current/kafka-rest/quickstart.html# detail out how to change broker settings programmatically. For instance. I'd like to change topic retention via REST. 

Using the cli one can do so via `kafka-topics --zookeeper localhost:2181 --alter --topic ${topicName} --config retention.ms=100000`. However, its unclear how to do so using REST-Proxy.

It would be great if the documentation could be extended accordingly, or be more clear about the scope of the API in case topics configuraiton changes not possible (yet?).

**Comment by MarkC0x** [comment]
Hi @holgerbrandl 

You can make such topic setting changes via the new REST Proxy API v3, but bear in mind that this is currently only released as a preview feature.

For example to use the Rest Proxy API to Change the Setting for “retention.ms”:

```
curl -X PUT -H "Content-Type: application/vnd.api+json" --data '{"data":{"attributes":{"value":"100000"}}}'  http://localhost:8082/v3/clusters/[Cluster-ID]/topics/test-topic/configs/retention.ms
```

You can then check the updated configuration value with the following:

```
curl -X GET -H "Accept: application/vnd.api+json" http://localhost:8082/v3/clusters/[Cluster-ID]/topics/test-topic/configs/retention.ms
```

```
{
  "data": {
    "id": "crn:///kafka=[Cluster-ID]/topic=test-topic/config=retention.ms",
    "links": {
      "self": "http://localhost:8082/v3/clusters/[Cluster-ID]/topics/test-topic/configs/retention.ms"
    },
    "attributes": {
      "cluster_id": "[Cluster-ID]",
      "topic_name": "test-topic",
      "name": "retention.ms",
      "value": "100000",
      "is_default": false,
      "is_read_only": false,
      "is_sensitive": false
    },
    "type": "KafkaTopicConfig"
  }
}
```


Note: If you need to find your cluster ID programmatically using the Rest Proxy API, then you can use the following command:

```
curl -X GET -H "Accept: application/vnd.api+json" http://localhost:8082/v3/clusters
```

**Comment by holgerbrandl** [comment]
Awesome, thanks @MarkC0x . Your suggestion worked perfectly for me. I wonder why this is not part of the official documentation.

From my end this ticket can be closed. However, I leave it to the repo maintainers to close it since they may want to actually adjust the docs to include this valuable information first.

**Comment by rigelbm** [comment]
Hey @holgerbrandl. This API was not documented because it was still in preview mode on Confluent Platform 5.5.0. It will be GA on Confluent Platform 6.0.0 (coming out soon!) and it will be fully documented there.

**Comment by xialincrm** [comment]
@MarkC0x : Hi, I used the your Put request to test, but got error:
```
{'data': {'attributes': {'value': '259200000'}}}
415 {"error_code":415,"message":"HTTP 415 Unsupported Media Type"}
```

I tried setting header Content-Type: application/vnd.api+json, application/vnd.kafka.json.v2+json. But none of them work. Any clues?  Thanks!

**Comment by xialincrm** [comment]
Hey @rigelbm , are we planning to add this topic config update in the official doc?
