### ISSUE TITLE
Trying to delete a topic using the v3 APi and getting "error_code": 50003

### ISSUE THREAD

**Issue by leandrohmvieira** [confluentinc/kafka-rest#681]
using curl DELETE http://kafka_ip:port/v3/clusters/cluster_id/topics/topic_name and for any topic that I try to delete I get this error below:

{
    "error_code": 50003,
    "message": "Call(callName=deleteTopics, deadlineMs=1590530562772) timed out at 1590530562773 after 596 attempt(s)"
}

I'm using docker cp-Kafka 5.5.0, and other operations, like Get Topic v3 is working, and I don't know what it might be, any guess?

**Comment by MarkC0x** [comment]
Unfortunately that isn't much to go on, as 50003 is a fairly generic (albeit retriable) error, and timeouts can happen for any number of reasons.

Can you provide your `docker-compose.yml` file if possible (to try and recreate), or perhaps more information from Rest Proxy, using something like `docker logs rest-proxy`?

**Comment by leandrohmvieira** [comment]
Thanks for the tip @MarkC0x , I totally forget about the docker logs, I just checked them and the problem was not on the rest API but on the Kafka Broker itself.
