### ISSUE TITLE
How to correctly map details to Kafka SSL parameters?

### ISSUE THREAD

**Issue by lhmzhou** [confluentinc/kafka-rest#702]
Trying to configure SSL authentication for Kafka, and getting SSL handshake failure with Kafka. Has anyone tripped on this rabbit hole?

> Java Stack Trace: com.abinitio.universal.error.StructuredException: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed
> 	at com.abinitio.kafka.version10x.AbKafkaProducer10.publish(AbKafkaProducer10.java:389)
> 	at com.abinitio.kafka.common.KafkaProducerBase.unipub_data(KafkaProducerBase.java:118)
> 	at com.abinitio.continuous_flow.universal.UniPublisher.handle_MSG_DATA(UniPublisher.java:251)
> 	at com.abinitio.continuous_flow.universal.UniProtocol.main_loop(UniProtocol.java:916)
> 	at com.abinitio.kafka.common.KafkaProducerBase.mainLoop(KafkaProducerBase.java:224)
> 	at com.abinitio.kafka.KafkaPublish.main(KafkaPublish.java:39)
> Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed
> 	at org.apache.kafka.clients.producer.KafkaProducer$FutureFailure.<init>(KafkaProducer.java:1132)
> 	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:831)
> 	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:768)
> 	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:656)
> 	at com.abinitio.kafka.version10x.AbKafkaProducer10.publish(AbKafkaProducer10.java:372)

**Comment by rigelbm** [comment]
I think you mistook this project (Kafka REST Proxy) for the Kafka project. You should probably open this issue there. See https://issues.apache.org/jira/projects/KAFKA/issues/
