### ISSUE TITLE
Allow schema.registry.url config option to be a list of urls

### ISSUE THREAD

**Issue by granders** [confluentinc/kafka-rest#71]
The actual logic changes happen in Schema Registry clients and possible KafkaAvroSerializer etc, but doc string for `schema.registry.url` should be updated when that change is made.

See https://github.com/confluentinc/schema-registry/issues/157

**Comment by simplesteph** [comment]
That's actually important for resilience and mirroring how every other component from the confluent platform works (kafka bootstrap servers, zookeeper quorum, schema registry...)

**Comment by ewencp** [comment]
@simplesteph This has been fixed for quite awhile (in 1fdb9e3359f5171907bf4c3a5429033d910deacb, which looks like 2.0 and newer), we just lost track of this ticket.
