### ISSUE TITLE
Get records (/records) endpoint does not fetch records from the last committed offset

### ISSUE THREAD

**Issue by SowmyaSeshadri** [confluentinc/kafka-rest#727]
### **Description:** 

When you consume N messages, commit the offset of N-2 message, and when you hit the get records endpoint, it does not fetch from the last committed offset. Instead, it fetches only the future messages pushed into the topic. (Version 5.5.0)

### Steps to reproduce

**The following are the sequence of requests** -

**1. Create a consumer instance** 
```
curl --location --request POST 'https://localhost:6000/consumers/sampleGroup' \
--header 'Content-Type: application/vnd.kafka.v2+json' \
--data-raw '{
  "name": "sampleInstance",
  "format": "json",
  "auto.offset.reset": "earliest",
  "auto.commit.enable": "false"
}'
```

**2. Subscribe to the topic**
```
curl --location --request POST 'https://localhost:6000/consumers/sampleGroup/instances/sampleInstance/subscription' \
--header 'Content-Type: application/vnd.kafka.v2+json' \
--data-raw '{
  "topics": [
    "topicA"
  ]
}'
```

**3. Retrieve messages from the topic** - 

```
curl --location --request GET 'https://localhost:6000/consumers/sampleGroup/instances/sampleInstance/records' \
--header 'Accept: application/vnd.kafka.json.v2+json' 
```

**Response**: 
```
[ {
        "topic": "topicA",
        "key": "123",
        "value": {
            ...
        },
        "partition": 0,
        "offset": 150
} ]
```

**4. Commit offset of n-2 message**
```
curl --location --request POST 'https://localhost:6000/consumers/sampleGroup/instances/sampleInstance/offsets' \
--header 'Content-Type: application/vnd.kafka.json.v2+json' \
--data-raw '{
  "offsets": [
    {
      "topic": "topicA",
      "partition": 0,
      "offset": 148
    }
  ]
}'
```

**5. Retrieve messages from the topic** - 
```
curl --location --request GET 'https://localhost:6000/consumers/sampleGroup/instances/sampleInstance/records' \
--header 'Accept: application/vnd.kafka.json.v2+json' 
```

**Response**: 
```
[ {
        "topic": "topicA",
        "key": "123",
        "value": {
            ...
        },
        "partition": 0,
        "offset": 151
} ]
```

As you see the below logs, though the last committed offset is `149` while retrieving the records using the `/consumers/sampleGroup/instances/sampleInstance/records` endpoint it reads only the future messages and not from the last committed offset. 

```
[sampleGroup,accums,0]::OffsetAndMetadata(offset=149, leaderEpoch=Optional.empty, metadata=, commitTimestamp=1596191265342, expireTimestamp=None)
```

**Workarounds:** 
1. Delete the consumer instance that I initially used and execute the same set of endpoints to consume messages. This time it picked up the offset that I last committed (149) and returned the messages as expected. _(Not the desired way of solving this issue)_

2. Use the fetch position endpoint(mentioned below) provided by REST proxy to seek to the desired offset and use our existing `/records` endpoint to fetch from that offset. (The offset that was committed previously will be overridden by this fetch position request)

```
curl --location --request POST 'https://localhost:6000/consumers/sampleGroup/instances/sampleInstance/positions' \
--header 'Content-Type: application/vnd.kafka.json.v2+json' \
--data-raw '{
  "offsets": [
    {
      "topic": "topicA",
      "partition": 0,
      "offset": 148
    }
  ]
}'
```

**Questions**: 
1. Though we were able to overcome this issue by the above-mentioned workarounds, **is this an expected behavior?** We don't see any of these details mentioned in the Confluent REST Proxy documentation. 

2. Workaround #2 seems to fix this issue, but per the actual behavior of Kafka, we should be able to consume records from the last committed offset without removing the consuming instance. **Will that be fixed in the future versions of REST Proxy?**

**Comment by MarkC0x** [comment]
Hi @SowmyaSeshadri,

This is expected behavior, as the REST Proxy (and in fact any Kafka consumer AFAIK) will continue to process records sequentially while it is still active.  Once the consumer is removed (or times out from `consumer.instance.timeout.ms`) then the committed offset is used when the consumer is re-instantiated so it knows where to resume from.

If you wish to re-read messages from the topic, or seek back to a prior offset, then your second solution of using the `positions` request is the correct way to achieve this.

Cheers
Mark

**Comment by SowmyaSeshadri** [comment]
Thanks for the clarification @MarkC0x
