### ISSUE TITLE
Add TLS support

### ISSUE THREAD

**Issue by mastersingh24** [confluentinc/kafka-rest#75]
I know we can run kafka-rest behind a secure proxy / load balancer, but in many organizations TLS is also required between the secure proxy / load balancer and the actual endpoint.  Also, in some simple deployments there may not be a front-end gateway / load balancer.  

I believe this would need to be implemented in rest-utils but would need to be exposed here

**Comment by kjvalencik** [comment]
:+1: Although, I would be satisfied with just the ability to listen on a unix socket instead of a TCP port. This would allow a simple nginx proxy to provide TLS without any network traffic.

**Comment by ewencp** [comment]
Fixed by #200
