### ISSUE TITLE
Option for Dynamic Incrementing ID for Rest Proxy

### ISSUE THREAD

**Issue by WalterDalton** [confluentinc/kafka-rest#80]
Per the documentation: 

id
Unique ID for this REST server instance. This is used in generating unique IDs for consumers that do not specify their ID. The ID is empty by default, which makes a single server setup easier to get up and running, but is not safe for multi-server deployments where automatic consumer IDs are used

The thought behind dynamic or incrementing IDs (perhaps kept straight in zookeeper) is that with Mesos, I can run the Rest Proxy in Marathon. Since I am using one common config, each instance would need to  use a "new id" (essentially a new config file for each instance) If we instead had an option to use prefix(incrementingid) then we could just scale up and down with a single config on Mesos.  Scaling would be automatic, rather than manual.  It makes each instance of the rest-proxy truly independent.  (seems to be a good goal). I know Mesos support isn't really a huge push, nor is "making it easier for mesos", however I think the idea behind making this just fire and forget on scaling could help folks even without Mesos.

**Comment by ewencp** [comment]
@WalterDalton This is changing in the next version. #67 has the actual change. Things were somewhat confusing between the server ID and the consumer instance ID. The new approach is to remove the server ID entirely. When creating consumers, we still respect the old set of options, but if you just specify a consumer group and no consumer instance ID, it'll fall back on generating one randomly using a UUID to ensure uniqueness.

This creates URLs that are a little bit messier, but makes it a lot easier to run in environments like you're talking about. This change will be included in the next release.

Would that approach work for your setup?

**Comment by WalterDalton** [comment]
Yes this should work. Thank you
