### ISSUE TITLE
Failing silently inside docker container

### ISSUE THREAD

**Issue by AndrewSwerlick** [confluentinc/kafka-rest#82]
I've trying to run the rest proxy inside a docker container using the confluent/platform image. I'm using docker compose to expose the zookeper and schema registry services running in other containers. I can start the rest service and it runs for a brief moment before failing. Here's the output to the console

    SLF4J: Class path contains multiple SLF4J bindings.
    SLF4J: Found binding in [jar:file:/usr/share/java/kafka/slf4j-log4j12-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    SLF4J: Found binding in [jar:file:/usr/share/java/confluent-common/slf4j-log4j12-1.7.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    SLF4J: Found binding in [jar:file:/usr/share/java/kafka-rest/slf4j-log4j12-1.7.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
    SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]

I'm running the service with `/etc/kafka-rest# kafka-rest-start /etc/kafka-rest/kafka-rest.properties`

My properties file looks like this 

    schema.registry.url=http://schemaRegistry:8081
    zookeeper.connect=zookeeper:2181
    id=1

I've tested those url's from inside of the container and they are correct. Note I am using the confluentinc images for zookeeper and the schema-registry.

**Comment by AndrewSwerlick** [comment]
If it helps here are the relevant portions of my docker-compose.yml file

    zookeeper:
      image: confluent/zookeeper
    kafka:
      image: confluent/kafka
      links:
        - zookeeper
      environment:
        - KAFKA_BROKER_ID=0
    schemaRegistry:
      image: confluent/schema-registry
      links:
        - zookeeper
        - kafka
      environment:
        - SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL=none
    kafkaRest:
      image: confluent/platform
      links:
        - schemaRegistry
        - zookeeper
      command: kafka-rest-start /etc/kafka-rest/kafka-rest.properties

**Comment by ewencp** [comment]
The silent exit is because a log4j.properties file is missing from the package -- see #69. If you put a log4j.properties file in /etc/kafka-rest/ (e.g. https://github.com/confluentinc/kafka-rest/blob/master/config/log4j.properties), it should log properly.

I'm not very familiar with docker-compose, but it looks like you're just using the published images, so how did you get the kafka-rest.properties into the image? I tested this and once I ran an image with both the log4j.properties and kafka-rest.properties it still crashed, but it looks like its just because of the docker configuration:

```
kafkarest_1      | [2015-05-22 23:19:26,642] ERROR Server died unexpectedly: org.apache.kafka.common.config.ConfigException: DNS resolution failed for url in bootstrap.servers: a96f21a2a076:9092 (io.confluent.kafkarest.Main:43)
```

This looks like an error due to the wrong hostname being put into Zookeeper. You probably need to set the advertised.host.name config in the Kafka broker config.

**Comment by AndrewSwerlick** [comment]
My apologies. I accidentally left out a line of the docker-compose.yml where I was mounting the properties file as a volume. I added a log4j.properties exactly like the link you posted in /etc/kafka-rest/config/log4j.properties. I also moved kafka-rest.properties in that folder. I still seem to be having the same issue though, and not getting the last error you posted. Here is the updated docker-compose.yml

    zookeeper:
      image: confluent/zookeeper
    kafka:
      image: confluent/kafka
      links:
        - zookeeper
    schemaRegistry:
      image: confluent/schema-registry
      links:
        - zookeeper
        - kafka
      environment:
        - SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL=none
    kafkaRest:
      image: confluent/platform
      links:
        - schemaRegistry
        - zookeeper
      command: kafka-rest-start /etc/kafka-rest/config/kafka-rest.properties
      volumes:
        - ./kafka-rest:/etc/kafka-rest/config

**Comment by ewencp** [comment]
The path it looks for the log4j.properties file in is `/etc/kafka-rest/log4j.properties`, no `config` in the path. I think the rest looks ok now.

If you need to specify the path for the log4j.properties file (or just want to set it explicitly to make sure it's set to exactly what you want), you can set the environment variable `KAKFAREST_LOG4J_OPTS`. You can see how we try to auto-detect the appropriate file in the `kafka-rest-run-class` script [here](https://github.com/confluentinc/kafka-rest/blob/master/bin/kafka-rest-run-class#L30), and you should be able to see how to set the option correctly from the examples there.

**Comment by AndrewSwerlick** [comment]
Awesome, got everything working. To solve the other problem you mentioned, I just added an environment variable to override the advertised host name. For others who may be attempting to do the same thing here's my final docker.yml

    zookeeper:
      image: confluent/zookeeper
    kafka:
      image: confluent/kafka
      links:
        - zookeeper
      environment:
        - KAFKA_ADVERTISED_HOST_NAME=kafka
    schemaRegistry:
      image: confluent/schema-registry
      links:
        - zookeeper
        - kafka
      environment:
        - SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL=none
    kafkaRest:
      image: confluent/platform
      links:
        - schemaRegistry
        - zookeeper
        - kafka
      command: kafka-rest-start /etc/kafka-rest/config/kafka-rest.properties
      volumes:
        - ./kafka-rest:/etc/kafka-rest

**Comment by ewencp** [comment]
Awesome, glad you got it working! I'm going to close this since the issue with kafka-rest is a dup of #69, but feel free to reopen if you run into any further issues.

**Comment by rebyn** [comment]
Got the stack up & running thanks to your `docker-compose.yml`, thanks @AndrewSwerlick!
