### ISSUE TITLE
Rest Api

### ISSUE THREAD

**Issue by tech7857** [confluentinc/kafka-rest#821]
Hi

i am working on writing a producer to post messages to Kafka Topic. I will be posting around 100k messages per day.

I was wondering if I can go ahead and use the Kafka Rest Api for posting or write a confluent producer code.

any consideration I should be aware. Which one will be most appropriate for my scenario.

Thanks

**Comment by axisc** [comment]
@tech7857 A lot of this depends on - 
  * throughput expectations.
  * infra on which the Kafka REST is hosted.

Largely, without knowing all the details of your workload, I think it should be fine, but do consider scaling the deployment if need be.
