### ISSUE TITLE
Unable to deserialise avro on kafka REST

### ISSUE THREAD

**Issue by knservis** [confluentinc/kafka-rest#83]
Hi, 

I am not sure whether there is a bug or there is some misconfiguration and looking through the code briefly I did find the problem. 

I am creating a consumer as in the Quickstart example: 

> curl -X POST -H "Content-Type: application/vnd.kafka.v1+json" --data '{"id": "my_instance", "format": "avro"}' http://kafka-0.internal:8082/consumers/my_avro_consumer

Then I am trying to consume some messages:

> curl -X GET -H "Accept: application/vnd.kafka.avro.v1+json"  http://kafka-0.internal:8082/consumers/my_avro_consumer/instances/my_instance/topics/valid-events

But I get the error:

> {"error_code":50002,"message":"Kafka error: Error deserializing Avro message for id -1"}

The console consumer can deserialise events from the same topic just fine and I know I used to get this error when the avro messages were not properly formatted (with the magic byte and the schema id from the registry), but after fixing those and getting them to work with the avro console consumer, I am still unable to use the REST consumer. 

Can anyone give me any insights as to why this may be? 

TIA

**Comment by ewencp** [comment]
The error message indicates that it didn't even get to parse the schema ID from the message. There are only two things that happen during parsing that early: checking the magic byte and reading the ID (an integer immediately following the magic byte). It looks like we should improve the error handling so we can track the issue back to it's real source, but my guess would be that the magic byte doesn't even match. The only other thing that makes sense is that the message was too short to read off the ID.

How did you produce the data in the topic? Is there a chance you produced some other data into the topic as well and that's causing the problem?

If you aren't sure, you could try creating a binary consumer and dumping the messages that way. We could then just check for any messages where the first few bytes don't have the correct values.

**Comment by tigerquoll** [comment]
In case others have had the same issue - the console consumer by default does not attempt to deserialize the record key unless property "print.key" is overridden to "true" on the command line, so any issues with deserializing keys (such as using "kafka.serializer.StringEncoder" to encode key values where the rest proxy expects both key and value to *both* be encoded with "io.confluent.kafka.serializers.KafkaAvroSerializer"), will likely not be highlighted by using the console consumer.

Some suggestions for the confluent folks - 
1. Could you provide a clearer error message on whether the deserializing error is with the key or the value portion of the Kafka Record?
2. (not so clear cut) Explore options on allowing keys pulled from topics to not assumed to be avro encoded?

**Comment by wakurth** [comment]
Hi @knservis ,

How are you producing the message? I was getting this same exact error when producing messages from node-rdkafka. It turned out that (at least at present time) the release of the library had a bug around null terminating string key's and not supporting buffered key types. Here's a link to that bug: https://github.com/Blizzard/node-rdkafka/issues/189

I would try to consume the message from a more raw consumer (e.g. one that just gives you the raw message and doesn't try to deserialize or format anything. Then look at the value of the key. In my case, it was an empty string which was causing this issue.

**Comment by knservis** [comment]
Hi @wakurth this was a long time ago. As far as I remember the message was produced using the standard kafka and avro library for java and the schema was in the schema registry or using the REST API and curl I really cannot remember which of the two. Back then I thought the error message had something to do with the REST API somehow not picking up the schema id, but the error message was non-informative. Sorry I probably should have added that info back then.

**Comment by the4thamigo-uk** [comment]
We have also seen this issue. We have a topic with a string key and avro payload. We can deserialize this topic using many other tools, but the kafka REST proxy fails with the above error.

Did anyone figure out the solution/workaround to this?

**Comment by Chloejay** [comment]
the same issue I have, ```
{"error_code":50002,"message":"Kafka error: Error deserializing Avro message for id -1"}```

the error message is, 
```
ERROR Unexpected exception in consumer read task id=io.confluent.kafkarest.ConsumerReadTask@644ff74  (io.confluent.kafkarest.ConsumerReadTask:169)
io.confluent.rest.exceptions.RestServerErrorException: Kafka error: Error deserializing Avro message for id -1
	at io.confluent.kafkarest.Errors.kafkaErrorException(Errors.java:206)
	at io.confluent.kafkarest.ConsumerReadTask.doPartialRead(ConsumerReadTask.java:166)
	at io.confluent.kafkarest.ConsumerManager$RunnableReadTask.run(ConsumerManager.java:422)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
```
can someone help me look up this error? any hint is welcome!
