### ISSUE TITLE
POST topic with different schema name

### ISSUE THREAD

**Issue by reneveyj** [confluentinc/kafka-rest#867]
Prior to 6.2, I was able to POST an event to https://docs.confluent.io/platform/6.2.0/kafka-rest/api.html#post--topics-(string-topic_name) with a **key_schema_id** and **value_schema_id**  corresponding to a subject name that was different from the topic I was sending it to.

Now I get an error saying: `Error when fetching schema version. subject = ..., schema = ...`

Is there any way to be able to do that again?

**Comment by paulolimarb** [comment]
Hi @reneveyj 

Do you resolved this question? If yes, you can share your solution?

Thanks

**Comment by reneveyj** [comment]
> Do you resolved this question? If yes, you can share your solution?

Hi @paulolimarb, I haven't tried this again, but I worked around the problem by changing the schema name to match the topic. Changing the topic name strategy on the schema registry could maybe also work.

Cheers

**Comment by paulolimarb** [comment]
Hi @reneveyj 

When I create schema name to match the topic, it works for me too. But on my case, the application has schemas name different of topic. And we cannot change... :-(. 

Thanks for your reply.

**Comment by reneveyj** [comment]
@paulolimarb I just tested it again with Confluent 7.1.1 and it looks like it works now. Maybe it has been fixed inbetween 6.2 and 7.1.1.
