### ISSUE TITLE
Kafka Rest 

### ISSUE THREAD

**Issue by Muddam0234** [confluentinc/kafka-rest#887]
Hi All,

I know if we are user CURL cmd it will consume and close, but i need my rest consumer API continually need to run. so Is there any possible, can we write Kafka rest consumer (for continually running like connector).

**Comment by axisc** [comment]
Thanks for raising this issue @Muddam0234.

At this time, Consume API still follows a Request response model, so there is no way to keep the connection active beyond the scope of the single request.
