### ISSUE TITLE
Handle large number of schemas

### ISSUE THREAD

**Issue by ewencp** [confluentinc/kafka-rest#91]
See related issue: confluentinc/schema-registry#172

When many requests come in for the same topic with the same schema and do not use the schema ID (e.g., the first request from many different clients), each one is registered via the serializer (see AvroRestProducer). However, because the serializer uses an IdentityHashMap, any cached schemas that are equivalent are not used, which results in a) an unnecessary HTTP request and b) a *different* entry in the IdentityHashMap for the same schema. This is a) slower than necessary and b) eventually exhausts the number of entries allowed in the cache (`max.schemas.per.subject`). One solution to this problem if the schema-registry implementation isn't going to detect these identical schemas would be to do deduplication at the kafka-rest level. This is a case where deduplication via the more expensive equals() check is actually valid since the REST proxy is expected to end up with many different instances of the same schema.

**Comment by thieman** [comment]
Our clients restart frequently (auto-scaling plus continuous deployment) and we are hitting this problem constantly. We have to restart our REST proxies every couple of hours to flush the identity map.

**Comment by criccomini** [comment]
+1 We just got hit by this as well.

> This is a case where deduplication via the more expensive equals() check is actually valid since the REST proxy is expected to end up with many different instances of the same schema.

I would also argue that if you're using REST proxy, the cost of .equals() relative to the overhead of the REST proxy is much smaller, compared to .equals() in an embedded Java/Python client.

**Comment by criccomini** [comment]
Can this be as simple as just switching identity hashmap back to a regular hashmap?

**Comment by jdehrlich** [comment]
Due to the way the identity hashmap is wired in via the serializer, it seems like switching back to a regular hashmap for kafka-rest is more effort and we think it's better to just add a cache in the AvroRestProducer, any objections? @ewencp unless you've already started on this, I will submit a patch if you approve of this solution.

**Comment by criccomini** [comment]
PR for this is up at https://github.com/confluentinc/kafka-rest/pull/222, I believe.

**Comment by criccomini** [comment]
Nudge.

**Comment by crumley** [comment]
👍 

I have this issue as well. Larger number of producers + frequent restarts cause this to happen fairly often. The cost of doing an equals check is going to be much more efficient than a network round trip to the schema registry... not to mention can be easily handled by scaling the rest-proxy layer should the cpu overhead become too much.

**Comment by criccomini** [comment]
Ping

**Comment by ewencp** [comment]
Fixed by #222
