### ISSUE TITLE
Docs: Unclear default partitioning behavior

### ISSUE THREAD

**Issue by randa1** [confluentinc/kafka-rest#92]
When using the POST /topics/{topic} endpoint to produce a message:
1. If record.partition is not explicitly passed, is the record.key used as partitioning key?
2. Which partitioning scheme is used when sending the message to Kafka? Is it the default Kafka partitioner (hash(key)%partitions)? 
3. Is there a way to override the partitioning behavior other than specifying record.partition?

I'm sorry if these questions are trivial, I've couldn't find a conclusive statement in the docs and I may have some terminology gaps as I'm only getting into Kafka and Confluent.

**Comment by hachikuji** [comment]
1. Yes, record.key is the partitioning key in the absence of record.partition.
2. In the absence of record.partition, we delegate partition assignment to KafkaProducer with the default partitioner.
3. Other than exposing record.partition, we don't currently provide a way to change the partition assignment strategy. Do you have a use case where this feature would be helpful?

And I'll take a look at updating the docs to make the partitioning strategy clearer.

**Comment by randa1** [comment]
Regarding #3 - I can't really think of anything right now, record.partition is probably enough.
Thanks for the quick reply.

**Comment by miguno** [comment]
@hachikuji: Have we checked whether the docs could be improved?  If so, can we close this ticket?

**Comment by hachikuji** [comment]
@miguno Sorry, forgot about this. Just opened GH-108 to fix.
