### ISSUE TITLE
Modify the number of partitions 

### ISSUE THREAD

**Issue by ss666** [confluentinc/kafka-rest#926]
It seems that the **number of partitions** can not be altered in default mode or expert mode.[https://docs.confluent.io/platform/current/control-center/topics/edit.html#c3-config-topic-params]

Does it mean I could only alter this parameter by Kafka CLI commands? Just wondering the intention of setting this parameter un-configurable in Control Center UI?

**Comment by OneCricketeer** [comment]
This project is not Control Center, but yes, it's recommended you restrict partition modifications to administrators with CLI access
