### ISSUE TITLE
How to restrict to publish message to specific topic 

### ISSUE THREAD

**Issue by raje143r** [confluentinc/kafka-rest#943]
Hi Team,
Could you please suggest me how to control to publish message to specific topic and to list only specific topic name which have created for specific kafka rest client. 
For ex: i have 3 topics... Topic1, topic2, topic3...  Among these only Topic2 is used by kafka rest client. But still rest client can see list of all topics and can publish to other topics(Topic1,Topic3) as well. How to restrict to particular topic for my client? 
Thankyou in advance

**Comment by axisc** [comment]
@raje143r Authorization in Kafka REST can be enforced using Kafka ACLs. When creating an ACL, you can specify the permissions and the scope (Topic2) and then allow the Kafka REST client to only use these credentials as defined in the ACL.

Please refer to this [documentation](https://docs.confluent.io/platform/current/kafka/authorization.html#authorization-in-the-rest-proxy-and-sr) to get details on how to proceed.

Hope this helps. Feel free to reach out if you have more questions.
