### ISSUE TITLE
DOCS-13509 Documents on confluent site very out of date? 

### ISSUE THREAD

**Issue by nuria** [confluentinc/kafka-rest#971]
Documents on confluent site very out of date? 

The documentation here: https://docs.confluent.io/platform/current/kafka-rest/api.html#blocklist seems very out of date. For example, features like 'allowlist' (instead of a 'blocklist') that are already functional are not mentioned.

**Comment by axisc** [comment]
Thanks for raising this issue, @nuria . We will investigate this internally and update the doc accordingly.

**Comment by londoncalling** [comment]
@axisc , @nuria , per this PR and https://confluentinc.atlassian.net/browse/DOCS-13509, Most of the Kafka REST docs are now autogenerated from the APIs. The Blocklist was added manually by @addisonhuddy , a long time ago. I'll need a Dev contact to show me what needs to be added, or at the very least to point me to where I can see the new features in the code.

**Comment by nuria** [comment]
As you can see here on git log below the allowlist is +1 year old,
there are similar points in the code where docs lag behind
significantly in very meaningful ways.

kafka-rest % git log
./kafka-rest/src/test/java/io/confluent/kafkarest/integration/accesslist/ResourceBlocklistTest.java
commit 3fde83c645750091e730842c4a6a4214bb3465a3
Author: ehumber ***@***.***>
Date:   Mon Jan 24 15:04:20 2022 +0000

    KREST-3660 Move to Junit 5 (#964)

    I tested by explicitly removing the junit 4 that came in via
jersey via kafka rest and found a couple of junit 4 ommissions.

commit 98462f1119b0d15d7aa993753f28792893fb7fc9
Author: Dimitar Dimitrov ***@***.***>
Date:   Thu Mar 18 13:07:53 2021 +0200

    KREST-771 Implement an allowlist for API endpoints. (#823)

    When specified, an allowlist disables all endpoints but the ones
    enumerated in it. An allowlist and a blocklist can be specified
    together in which case the blocklist can further constrain the
    allowlist, including blocking specific methods under a resource
    class that is present in the allowlist.

**Comment by axisc** [comment]
@nuria please review the updated documentation here https://docs.confluent.io/platform/current/kafka-rest/api.html#accesslists and feel free to raise another issue if there are any follow ups.
