### ISSUE TITLE
Avro producer compression codec?

### ISSUE THREAD

**Issue by edrex333** [confluentinc/kafka-rest#98]
What is the default Avro producer compression codec and is this configurable?

**Comment by ewencp** [comment]
The default is the same as the default on the new producer, which is `none`. You can override these settings by passing producer (or consumer) settings directly in the REST proxy config. So just add a `compression.type` config and it will apply to all messages, not just Avro.

For general questions like this, we also have a mailing list: https://groups.google.com/forum/#!forum/confluent-platform

**Comment by edrex333** [comment]
Thanks, I appreciate the help! I'll use the mailing list in the future.
